lookups/lookup-get-basic-example-1/lookup-get-basic-example-1.cs, lookups/lookup-get-basic-example-2/lookup-get-basic-example-2.cs, lookups/lookup-get-carrier-cname-example-1/lookup-get-carrier-cname-example-1.json.curl, pricing/get-lookup-pricing/get-lookup-pricing.py, pricing/get-messaging-country/get-messaging-country.cs, pricing/get-messaging-country/get-messaging-country.java, pricing/get-messaging-country/get-messaging-country.py, pricing/get-phone-number-country/get-phone-number-country.cs, pricing/get-phone-number-country/get-phone-number-country.js, pricing/get-phone-number-country/get-phone-number-country.py, pricing/get-voice-country/get-voice-country.cs, pricing/get-voice-country/get-voice-country.py, pricing/get-voice-number/get-voice-number.cs, pricing/list-messaging-countries/list-messaging-countries.cs, pricing/list-messaging-countries/list-messaging-countries.py, pricing/list-phone-number-countries/list-phone-number-countries.cs, pricing/list-phone-number-countries/list-phone-number-countries.js, pricing/list-phone-number-countries/list-phone-number-countries.py, pricing/list-phone-number-countries/list-phone-number-countries.rb, pricing/list-voice-countries/list-voice-countries.cs
This covers code fixes related to bugs and styling in `lookups` and `pricing`
=> Review lookups and pricing code samples

ip-messaging/channels/accept-invite/accept-invite.js, ip-messaging/channels/create-channel/create-channel.js, ip-messaging/channels/delete-a-channel/delete-channel.js, ip-messaging/channels/detect-channel-states/create-channel.js, ip-messaging/channels/get-messages/get-messages.js, ip-messaging/channels/join-a-channel/join-channel.js, ip-messaging/channels/message-added/message-added.js, ip-messaging/channels/retrieve-channels/retrieve-channels.js, ip-messaging/channels/send-invite/send-invite.js, ip-messaging/channels/send-messages/send-message.js, ip-messaging/consumption/consumption-report/consumption-report.js, ip-messaging/consumption/message-read-status/message-read-status.js, ip-messaging/typing-indicator/typing-indicator-send/typing-indicator-send.js, ip-messaging/typing-indicator/typing-indictor-consume/typing-indictor-consume.js, ip-messaging/users/client-initialization/create-channel.js, video/users/token-generation-server/token.cs, video/users/token-generation/token-retrieval.js
Make it ready to be imported as Fragment in the new CMS
=> Migrate IP-Messaging/Usage

rest/sip-in/create-acl-address/meta.json, rest/sip-in/create-domain/meta.json, rest/sip-in/create-ip-acl/meta.json, rest/sip-in/delete-access-mapping/meta.json, rest/sip-in/delete-address-instance/meta.json, rest/sip-in/delete-domain-instance/meta.json, rest/sip-in/delete-ip-acl/meta.json, rest/sip-in/get-acl-address/meta.json, rest/sip-in/get-acl-addresses/meta.json, rest/sip-in/get-acl-list/meta.json, rest/sip-in/get-mappings-instance/meta.json, rest/sip-in/map-list-domain/meta.json, rest/sip-in/update-address-instance/meta.json, rest/sip-in/update-domain-instance/meta.json, rest/sip-in/update-ip-acl-instance/meta.json
Until april 22th, 2016: Multiples snippets described.
=> Fix Sip of meta.json until 75%

rest/conference/instance-get-example-1/meta.json, rest/conference/list-get-example-1/meta.json, rest/conference/list-get-example-2/meta.json, rest/conference/list-get-example-3/meta.json, rest/conference/list-get-example-4/meta.json
Adding context to the titles in meta.json file
=> Change meta.json titles

rest/making-calls/example-1/example-1.cs, rest/making-calls/example-1/example-1.java, rest/making-calls/example-1/example-1.js, rest/making-calls/example-1/example-1.php, rest/making-calls/example-1/example-1.py, rest/making-calls/example-1/example-1.rb, rest/making-calls/example-1/meta.json, rest/making-calls/example-2/example-2.cs, rest/making-calls/example-2/example-2.java, rest/making-calls/example-2/example-2.js, rest/making-calls/example-2/example-2.json.curl, rest/making-calls/example-2/example-2.php, rest/making-calls/example-2/example-2.py, rest/making-calls/example-2/example-2.rb, rest/making-calls/example-2/example-2.xml.curl, rest/making-calls/example-2/meta.json
=> never gonna give you up

monitor/alerts/list-get-example-warnings-apr01-apr30/list-get-example-warnings-apr01-apr30.py
Fix 2nd start_date to end_date.
=> fix end_date

rest/keys/using-keys-example/example.js, rest/keys/using-keys-example/example.json.curl, rest/keys/using-keys-example/example.php, rest/keys/using-keys-example/meta.json
=> API keys examples

ip-messaging/channels/accept-invite/accept-invite.m, ip-messaging/channels/accept-invite/accept-invite.swift, ip-messaging/channels/create-channel/create-channel.m, ip-messaging/channels/create-channel/create-channel.swift, ip-messaging/channels/delete-a-channel/delete-a-channel.m, ip-messaging/channels/delete-a-channel/delete-a-channel.swift, ip-messaging/channels/detect-channel-states/detect-channel-states.m, ip-messaging/channels/detect-channel-states/detect-channel-states.swift, ip-messaging/channels/detect-member-states/detect-member-states.m, ip-messaging/channels/detect-member-states/detect-member-states.swift, ip-messaging/channels/get-messages/get-messages.m, ip-messaging/channels/get-messages/get-messages.swift, ip-messaging/channels/join-a-channel/join-a-channel.m, ip-messaging/channels/join-a-channel/join-a-channel.swift, ip-messaging/channels/message-added/message-added.m, ip-messaging/channels/message-added/message-added.swift, ip-messaging/channels/retrieve-channels/retrieve-channels.m, ip-messaging/channels/retrieve-channels/retrieve-channels.swift, ip-messaging/channels/send-invite/send-invite.m, ip-messaging/channels/send-invite/send-invite.swift, ip-messaging/channels/send-messages/send-messages.m, ip-messaging/channels/send-messages/send-messages.swift
- Updated to latest syntax compatible with 0.14.2
- Ensure Obj-C and Swift match functionality
- Code is now hosted in xcodeproject, so some formatting only-changes may occur in this commit only
=> Updates for IP Messaging 0.14.2

lookups/lookup-international-basic/lookup-international-basic.4.x.php, lookups/lookup-international-basic/lookup-international-basic.5.x.php, lookups/lookup-international-basic/lookup-international-basic.cs, lookups/lookup-international-basic/lookup-international-basic.java, lookups/lookup-international-basic/lookup-international-basic.js, lookups/lookup-international-basic/lookup-international-basic.json.curl, lookups/lookup-international-basic/lookup-international-basic.py, lookups/lookup-international-basic/lookup-international-basic.rb, lookups/lookup-international-basic/meta.json, lookups/lookup-international-basic/output/lookup-international-basic.json, lookups/lookup-national-basic/lookup-national-basic.4.x.php, lookups/lookup-national-basic/lookup-national-basic.5.x.php, lookups/lookup-national-basic/lookup-national-basic.cs, lookups/lookup-national-basic/lookup-national-basic.java, lookups/lookup-national-basic/lookup-national-basic.js, lookups/lookup-national-basic/lookup-national-basic.json.curl, lookups/lookup-national-basic/lookup-national-basic.py, lookups/lookup-national-basic/lookup-national-basic.rb, lookups/lookup-national-basic/meta.json, lookups/lookup-national-basic/output/lookup-national-basic.json
=> New examples for Lookup

guides/voice/record-calls-guide/record-outgoing-call/example-1.4.x.php, guides/voice/record-calls-guide/record-outgoing-call/example-1.5.x.php, guides/voice/record-calls-guide/record-twiml-transcribe/example.php, guides/voice/record-calls-guide/record-twiml/example.php
https://www.twilio.com/docs/admin/pages/1564/
=> Record Phone Calls in PHP

rest/messages/feedback-confirm/feedback-confirm.php
Not sure if the PHP library provides an API to create a Feedback.
=> Update snippet for send delivery confirmation feedback in PHP

rest/message/list-get-example-2/list-get-example-2.5.x.php, rest/message/list-get-example-2/list-get-example-2.js
This one completes the snippets for PHP and Node.js.
=> Retrieve modify message history

rest/message/list-get-example-2/list-get-example-2.rb
https://www.twilio.com/docs/admin/pages/1577/edit/
Update filtering messages snippets.
=> Retrieve and Modify Message History in Ruby

rest/message/list-get-example-2/list-get-example-2.6.x.java, rest/message/list-get-example-2/list-get-example-2.7.x.java
This should fix the broken build on master. Thanks for the heads up guys.
/cc @mosampaio, @mcelicalderon
=> Add missing dependencies for list-get-example Java examples

guides/voice/record-calls-guide/record-outgoing-call/example-1.6.x.java, guides/voice/record-calls-guide/record-outgoing-call/example-1.7.x.java
This one adds the record parameter for creating an outgoing call.
https://www.twilio.com/docs/guides/voice/record-phone-calls/java#make-and-record-an-outbound-call
=> Add Record Parameter for Creating an Outgoing Call

rest/test-credentials/test-sms-messages-example-1/meta.json, rest/test-credentials/test-sms-messages-example-1/test-sms-messages-example-1.4.x.php, rest/test-credentials/test-sms-messages-example-1/test-sms-messages-example-1.6.x.java, rest/test-credentials/test-sms-messages-example-1/test-sms-messages-example-1.cs, rest/test-credentials/test-sms-messages-example-1/test-sms-messages-example-1.json.curl, rest/test-credentials/test-sms-messages-example-1/test-sms-messages-example-1.py, rest/test-credentials/test-sms-messages-example-1/test-sms-messages-example-1.rb, rest/test-credentials/test-sms-messages-example-1/test-sms-messages-example-1.xml.curl, rest/test-credentials/test-sms-messages-example-2/meta.json, rest/test-credentials/test-sms-messages-example-2/test-sms-messages-example-2.4.x.php, rest/test-credentials/test-sms-messages-example-2/test-sms-messages-example-2.6.x.java, rest/test-credentials/test-sms-messages-example-2/test-sms-messages-example-2.cs, rest/test-credentials/test-sms-messages-example-2/test-sms-messages-example-2.json.curl, rest/test-credentials/test-sms-messages-example-2/test-sms-messages-example-2.py, rest/test-credentials/test-sms-messages-example-2/test-sms-messages-example-2.rb, rest/test-credentials/test-sms-messages-example-2/test-sms-messages-example-2.xml.curl, rest/test-credentials/test-sms-messages-example-3/meta.json, rest/test-credentials/test-sms-messages-example-3/test-sms-messages-example-3.4.x.php, rest/test-credentials/test-sms-messages-example-3/test-sms-messages-example-3.6.x.java, rest/test-credentials/test-sms-messages-example-3/test-sms-messages-example-3.cs, rest/test-credentials/test-sms-messages-example-3/test-sms-messages-example-3.json.curl, rest/test-credentials/test-sms-messages-example-3/test-sms-messages-example-3.py, rest/test-credentials/test-sms-messages-example-3/test-sms-messages-example-3.rb, rest/test-credentials/test-sms-messages-example-3/test-sms-messages-example-3.xml.curl
=> Update Examples to Use the Messages Resource

sync/rest/lists/query-list/output/retrieve-list.json, sync/rest/lists/query-list/query-list.cs, sync/rest/lists/query-list/query-list.json.curl, sync/rest/lists/query-list/query-list.php, sync/rest/lists/query-list/query-list.rb, sync/rest/maps/query-map/output/query-map.json, sync/rest/maps/query-map/query-map.cs, sync/rest/maps/query-map/query-map.json.curl, sync/rest/maps/query-map/query-map.php, sync/rest/maps/query-map/query-map.rb
... to Order (ASCending/DESCending)
=> Rename Direction list&map item query parameter

video/getting-started/connect-to-room/connect-to-room.js, video/getting-started/create-video-client/create-video-client.js, video/getting-started/handle-participants/handle-participants.js, video/getting-started/setup-local-media/setup-local-media.js, video/getting-started/use-participant-media/use-participant-media.js
@idelgado @aaalaniz @ptankTwilio
=> Add twilio-video.js Getting Started examples

video/getting-started/create-video-client/create-video-client.js, video/getting-started/setup-local-media/setup-local-media.js
=> Fix include instructions for twilio-video.js

rest/authorized-connect-apps/instance-get-example-1/meta.json, rest/authorized-connect-apps/list-get-example-1/meta.json, rest/connect-apps/instance-get-example-1/meta.json, rest/connect-apps/list-get-example-1/meta.json, rest/participant/instance-delete-example-1/meta.json, rest/participant/instance-get-example-1/meta.json, rest/participant/list-get-example-1/meta.json, rest/sip-in/get-domain-instance/meta.json, rest/sip-in/get-domains/meta.json, rest/taskrouter/reservations/redirect/meta.json
**Story**: [DEVED-1948](https://issues.corp.twilio.com/browse/DEVED-1948)
@kwhinnery we scanned the `api-snippets` repo to find out code examples that needs a more descriptive title.
=> Add Descriptive Titles on Code Samples

rest/test-credentials/test-sms-messages-example-1/output/test-sms-messages-example-1.xml, rest/test-credentials/test-sms-messages-example-1/test-sms-messages-example-1.js, rest/test-credentials/test-sms-messages-example-2/test-sms-messages-example-2.js, rest/test-credentials/test-sms-messages-example-3/test-sms-messages-example-3.js
[DEVED-1890](https://issues.corp.twilio.com/browse/DEVED-1890)
=> Use /Messages instead of the deprecated resource /SMS/Messages

.travis.yml
- Improve Travis.yml to try to speed up the builds.
- Add cache.
- Simplify commands.
- Fix indentations.
- Based on official docs from https://docs.travis-ci.com/user/speeding-up-the-build and https://docs.travis-ci.com/user/caching
d-( ʘ‿ʘ )_m
=> Improve Travis.yml

rest/participant/instance-get-example-1/output/instance-get-example-1.json, rest/participant/instance-get-example-1/output/instance-get-example-1.xml, rest/participant/instance-post-example-2/instance-post-example-2.json.curl, rest/participant/instance-post-example-2/instance-post-example-2.xml.curl, rest/participant/instance-post-example-2/meta.json, rest/participant/instance-post-example-2/output/instance-post-example-1.json, rest/participant/instance-post-example-2/output/instance-post-example-1.xml, rest/participant/list-get-example-1/output/list-get-example-1.json, rest/participant/list-get-example-1/output/list-get-example-1.xml
Kicking off getting hold snippets done. Still todo is write up examples for the next gen libs which support the hold param.
=> Adds Hold field and Example to Participant Snippits

guides/request-validation-sinatra/example-1/example-1.3.x.rb, guides/request-validation-sinatra/example-1/meta.json
- Add request-validation-sinatra examples.
- Rubocop clean and tidy.
- Add meta.
=> Add request-validation-sinatra

guides/request-validation-express/example-1/example-1.3.x.js, guides/request-validation-express/example-2/example-2.3.x.js
@joliveros could you help me out reviewing this pull request please?
=> Fix the request validation for Express examples

add-ons/lookups/payfone-tcpa-compliance/meta.json, add-ons/lookups/payfone-tcpa-compliance/payfone-tcpa-compilance.3.x.js, add-ons/lookups/payfone-tcpa-compliance/payfone-tcpa-compilance.5.x.cs, add-ons/lookups/payfone-tcpa-compliance/payfone-tcpa-compilance.5.x.php, add-ons/lookups/payfone-tcpa-compliance/payfone-tcpa-compilance.5.x.rb, add-ons/lookups/payfone-tcpa-compliance/payfone-tcpa-compilance.6.x.py, add-ons/lookups/payfone-tcpa-compliance/payfone-tcpa-compilance.7.x.java
Add examples for look up a phone number with Payfone TCPA Compliance Add-on.
=> Add add-ons next-gen examples for Payfone TCPA Compliance

video/users/token-generation-server/token-generation-server.6.x.py
This code breaks since the import is ConversationsGrant and we're needing a VideoGrant()
=> Change to VideoGrant

rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.2.x.js, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.3.x.js, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.4.x.cs, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.4.x.php, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.4.x.rb, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.5.x.php, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.5.x.py, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.6.x.py, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.7.x.java, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.json.curl, rest/subaccounts/exchanging-numbers-example-1/meta.json
Updates all except for old Python, which currently still works only for numbers owned by the main account
=> subaccount transfer example update

notifications/register/create-binding-server/create-binding-server-apn.5.x.cs, notifications/register/create-binding-server/create-binding-server-fcm.5.x.cs, notifications/register/create-binding-server/create-binding-server.5.x.cs, notifications/register/send-notification-1/send-notification-1.5.x.cs, notifications/register/send-notification-2/send-notification-2.5.x.cs, notifications/register/send-notification/send-notification.5.x.cs
This pull request adds the missing notification examples for C#.
Ref: [DEVED-2140](https://issues.corp.twilio.com/browse/DEVED-2140)
=> Add Notifications examples for C#

client/capability-token-2way/capability-token.5.x.cs, client/capability-token-incoming/capability-token.5.x.cs, client/capability-token-outgoing/capability-token.5.x.cs, client/capability-token/capability-token.5.x.cs, rest/access-tokens/ip-messaging-example/ip-messaging-example.5.x.cs, rest/access-tokens/video-example/video-example.5.x.cs, rest/taskrouter/jwts/taskqueue/example-1/example-1.5.x.cs, rest/taskrouter/jwts/worker/example-1/example-1.5.x.cs, rest/taskrouter/jwts/workspace/example-1/example-1.5.x.cs, rest/taskrouter/tasks/list/get/example-2/example-2.5.x.cs, rest/taskrouter/tasks/list/post/example-1/example-1.5.x.cs, tools/snippet-testing/model/dependency.rb, video/users/token-generation-server-rooms/token-generation-server.5.x.cs, video/users/token-generation-server/token-generation-server.5.x.cs
Issue: [DEVED-2166](https://issues.corp.twilio.com/browse/DEVED-2166)
This pull request updates the Twilio C# helper library to version 5.0.0-rca4.
Additionally, it fixes the examples that got affected because of the dependency update.
/cc @dprothero
=> [DEVED-2166] Test C# next-gen rca4

rest/access-tokens/ip-messaging-example/ip-messaging-example.5.x.cs, rest/access-tokens/video-example/video-example.5.x.cs, rest/taskrouter/jwts/taskqueue/example-1/example-1.5.x.cs, rest/taskrouter/jwts/worker/example-1/example-1.5.x.cs, rest/taskrouter/jwts/workspace/example-1/example-1.5.x.cs, rest/taskrouter/tasks/list/get/example-2/example-2.5.x.cs, rest/taskrouter/tasks/list/post/example-1/example-1.5.x.cs, security/signature_validation/signature_validation.2.x.js, security/signature_validation/signature_validation.3.x.js, security/signature_validation/signature_validation.5.x.cs, tools/snippet-testing/model/dependency.rb
=> Add signature-validation snippets for Node and C#

rest/access-tokens/voice-example/meta.json, rest/access-tokens/voice-example/voice-example.2.x.js, rest/access-tokens/voice-example/voice-example.3.x.js, rest/access-tokens/voice-example/voice-example.4.x.cs, rest/access-tokens/voice-example/voice-example.4.x.rb, rest/access-tokens/voice-example/voice-example.5.x.cs, rest/access-tokens/voice-example/voice-example.5.x.php, rest/access-tokens/voice-example/voice-example.5.x.py, rest/access-tokens/voice-example/voice-example.5.x.rb, rest/access-tokens/voice-example/voice-example.6.x.py, rest/access-tokens/voice-example/voice-example.7.x.java
=> Add snippet for creating access token with voice grant

authy/mobile-sdk/get-started/approve-deny-request/approve-deny-request.java, authy/mobile-sdk/get-started/approve-deny-request/approve-deny-request.m, authy/mobile-sdk/get-started/approve-deny-request/approve-deny-request.swift, authy/mobile-sdk/get-started/approve-deny-request/meta.json, authy/mobile-sdk/get-started/get-approval-requests/get-approval-requests.java, authy/mobile-sdk/get-started/get-approval-requests/get-approval-requests.m, authy/mobile-sdk/get-started/get-approval-requests/get-approval-requests.swift, authy/mobile-sdk/get-started/get-approval-requests/meta.json, authy/mobile-sdk/get-started/is-device-registered/is-device-registered.java, authy/mobile-sdk/get-started/is-device-registered/is-device-registered.m, authy/mobile-sdk/get-started/is-device-registered/is-device-registered.swift, authy/mobile-sdk/get-started/is-device-registered/meta.json, authy/mobile-sdk/get-started/register-device/meta.json, authy/mobile-sdk/get-started/register-device/register-device.java, authy/mobile-sdk/get-started/register-device/register-device.m, authy/mobile-sdk/get-started/register-device/register-device.swift, authy/mobile-sdk/get-started/setup-authy/meta.json, authy/mobile-sdk/get-started/setup-authy/setup-authy.java, authy/mobile-sdk/get-started/setup-authy/setup-authy.m, authy/mobile-sdk/get-started/setup-authy/setup-authy.swift
Add snippets for swift, objective c and Java code for the Authy Mobile SDK
=> Added Android and iOS code snippets for the Authy Mobile SDK

notifications/register/send-notification-1/send-notification-1.curl, notifications/register/send-notification-2/send-notification-2.curl
Two examples had parameter names wrong (Tags instead of Tag). Fixed.
=> Tags --> Tag fix

video/rooms/disconnect-from-room/disconnect-from-room.js
=> Remove references to "media".

fax/basic-receive/server.4.x.rb, fax/basic-receive/server.5.x.cs, fax/basic-receive/server.5.x.php, fax/basic-receive/server.6.x.py, fax/basic-receive/server.7.x.java
=> Deved 2333 fax quickstart server examples

wireless/sims/instance-get-example-1/output/instance-get-example-1.json, wireless/sims/instance-get-example-2/output/instance-get-example-2.json, wireless/sims/list-example-1/output/list-example-1.json
See: https://groups.google.com/forum/#!topic/twilio-programmable-wireless/Z4MWFEp3OFo
=> Updated to reflect new valid Sim status values

notifications/rest/notifications/send-notification-with-badge/meta.json, notifications/rest/notifications/send-notification-with-badge/send-notification-with-badge.json.curl
curl api snippet for sending a notification with badge
https://issues.corp.twilio.com/browse/DEVED-2217
=> Send notification with badge: curl snippet

notifications/rest/segments/list-segment/list-segment.json.curl, notifications/rest/segments/list-segment/meta.json, notifications/rest/segments/list-segment/output/list-segment.json, notifications/rest/users/add-user-to-segment/add-user-to-segment.json.curl, notifications/rest/users/add-user-to-segment/meta.json, notifications/rest/users/add-user-to-segment/output/add-user-to-segment.json, notifications/rest/users/create-user/create-user.json.curl, notifications/rest/users/create-user/meta.json, notifications/rest/users/create-user/output/create-user.json, notifications/rest/users/delete-user/delete-user.json.curl, notifications/rest/users/delete-user/meta.json, notifications/rest/users/delete-user/output/delete-user.json, notifications/rest/users/list-binding-of-user/list-binding.json.curl, notifications/rest/users/list-binding-of-user/meta.json, notifications/rest/users/list-binding-of-user/output/list-binding.json, notifications/rest/users/list-user/list-user.json.curl, notifications/rest/users/list-user/meta.json, notifications/rest/users/list-user/output/list-user.json, notifications/rest/users/remove-user-from-segment/meta.json, notifications/rest/users/remove-user-from-segment/output/remove-user-from-segment.json, notifications/rest/users/remove-user-from-segment/remove-user-from-segment.json.curl, notifications/rest/users/retrieve-user/meta.json, notifications/rest/users/retrieve-user/output/retrieve-user.json, notifications/rest/users/retrieve-user/retrieve-user.json.curl
https://issues.corp.twilio.com/browse/DEVED-2361
=> Add curl API snippets for new notify rest users and segments resources

rest/subaccounts/creating-subaccounts-example-1/creating-subaccounts-example-1.5.x.php
This PR attemps to solve [twilio-php/issues/412](https://github.com/twilio/twilio-php/issues/412)
=> Fixing subaccounts creation for v5.x in php

notifications/rest/bindings/create-binding/create-binding.3.x.js, notifications/rest/bindings/create-binding/create-binding.5.x.rb, notifications/rest/bindings/create-binding/create-binding.6.x.py, notifications/rest/bindings/list-binding/list-binding.6.x.py, notifications/rest/notifications/send-notification-detailed/send-notification-detailed.3.x.js, notifications/rest/notifications/send-notification-detailed/send-notification-detailed.5.x.cs, notifications/rest/notifications/send-notification-detailed/send-notification-detailed.5.x.php, notifications/rest/notifications/send-notification-detailed/send-notification-detailed.5.x.rb, notifications/rest/notifications/send-notification-detailed/send-notification-detailed.6.x.py, notifications/rest/notifications/send-notification-detailed/send-notification-detailed.7.x.java, notifications/rest/services/create-service/create-service.3.x.js, notifications/rest/services/create-service/create-service.5.x.cs, notifications/rest/services/create-service/create-service.5.x.php, notifications/rest/services/create-service/create-service.5.x.rb, notifications/rest/services/create-service/create-service.6.x.py, notifications/rest/services/create-service/create-service.7.x.java, notifications/rest/services/update-service/update-service.3.x.js, notifications/rest/services/update-service/update-service.5.x.cs, notifications/rest/services/update-service/update-service.5.x.php, notifications/rest/services/update-service/update-service.5.x.rb, notifications/rest/services/update-service/update-service.6.x.py, notifications/rest/services/update-service/update-service.7.x.java
Updates to API snippets for the notify team - [this doc outlines the requested changes](https://docs.google.com/document/d/18NcoMVpvRMCRPntpgsAO509YT_g4is23TxSiRgf7dZI/edit#heading=h.bfkbi6xr58v5). 
Most of these are simple parameter updates, but I'd appreciate an extra close look at [this commit](https://github.com/TwilioDevEd/api-snippets/commit/f0654fee0a2c31bffea41b1af3f700be7b47af03) to make sure I didn't mess any syntax up.
=> Notify snippets parameter updates

ip-messaging/rest/credentials/create-credentials/create-credentials.5.x.rb, ip-messaging/rest/credentials/delete-credentials/delete-credentials.5.x.rb, ip-messaging/rest/credentials/list-credentials/list-credentials.5.x.rb, ip-messaging/rest/credentials/retrieve-credentials/retrieve-credentials.5.x.rb, ip-messaging/rest/credentials/update-credentials/update-credentials.5.x.rb, ip-messaging/rest/members/add-member/add-member.5.x.rb, ip-messaging/rest/members/list-members/list-members.5.x.rb, ip-messaging/rest/members/remove-member/remove-member.5.x.rb, ip-messaging/rest/members/retrieve-member/retrieve-member.5.x.rb, ip-messaging/rest/messages/delete-messages/delete-messages.5.x.rb, ip-messaging/rest/messages/list-messages/list-messages.5.x.rb, ip-messaging/rest/messages/retrieve-messages/retrieve-messages.5.x.rb, ip-messaging/rest/messages/send-messages/send-messages.5.x.rb, ip-messaging/rest/messages/update-messages/update-messages.5.x.rb, ip-messaging/rest/users/create-user/create-user.5.x.rb, ip-messaging/rest/users/delete-user/delete-user.5.x.rb, ip-messaging/rest/users/list-users/list-users.5.x.rb, ip-messaging/rest/users/retrieve-user/retrieve-user.5.x.rb, ip-messaging/rest/users/update-user/update-user.5.x.rb
- messsages
- members
- users
- credentials
=> ruby 5.x samples updated for chat v2

ip-messaging/rest/credentials/create-credentials/create-credentials.6.x.py, ip-messaging/rest/credentials/delete-credentials/delete-credentials.6.x.py, ip-messaging/rest/credentials/list-credentials/list-credentials.6.x.py, ip-messaging/rest/credentials/retrieve-credentials/retrieve-credentials.6.x.py, ip-messaging/rest/credentials/update-credentials/update-credentials.6.x.py, ip-messaging/rest/messages/delete-messages/delete-messages.6.x.py, ip-messaging/rest/messages/list-messages/list-messages.6.x.py, ip-messaging/rest/messages/retrieve-messages/retrieve-messages.6.x.py, ip-messaging/rest/messages/send-messages/send-messages.6.x.py, ip-messaging/rest/messages/update-messages/update-messages.6.x.py, ip-messaging/rest/roles/create-role/create-role.6.x.py, ip-messaging/rest/roles/delete-role/delete-role.6.x.py, ip-messaging/rest/roles/list-roles/list-roles.6.x.py, ip-messaging/rest/roles/retrieve-role/retrieve-role.6.x.py, ip-messaging/rest/roles/update-role/update-role.6.x.py, ip-messaging/rest/users/create-user/create-user.6.x.py, ip-messaging/rest/users/delete-user/delete-user.6.x.py, ip-messaging/rest/users/list-users/list-users.6.x.py, ip-messaging/rest/users/retrieve-user/retrieve-user.6.x.py, ip-messaging/rest/users/update-user/update-user.6.x.py
Updating snippets to latest Python helper library version
=> Update Chat REST Python helper library snippets

video/rooms/join-room/join-room.swift
Updated the code snippet to reflect API changes.
=> Updated the Join-Room Code Snippet to reflect API changes

notifications/rest/users/delete-user/delete-user.3.x.js, notifications/rest/users/remove-user-from-segment/remove-user-from-segment.3.x.js
@atbaker Made minor fixes to notify code samples (replaced "delete()" with "remove()") can you check and merge, please.
=> Replaced "delete" with "remove" in node examples.

sync/rest/documents/create-document/create-document.5.x.cs, sync/rest/documents/delete-document/delete-document.5.x.cs, sync/rest/documents/list-documents/list-documents.5.x.cs, sync/rest/documents/retrieve-document/retrieve-document.5.x.cs, sync/rest/documents/update-document/update-document.5.x.cs, sync/rest/lists/create-list-item/create-list-item.5.x.cs, sync/rest/lists/create-list/create-list.5.x.cs, sync/rest/lists/delete-list-item/delete-list-item.5.x.cs, sync/rest/lists/delete-list/delete-list.5.x.cs, sync/rest/lists/list-lists/list-lists.5.x.cs, sync/rest/lists/query-list/query-list.5.x.cs, sync/rest/lists/retrieve-list-item/retrieve-list-item.5.x.cs, sync/rest/lists/retrieve-list/retrieve-list.5.x.cs, sync/rest/lists/update-list-item/update-list-item.5.x.cs, sync/rest/maps/create-map-item/create-map-item.5.x.cs, sync/rest/maps/create-map/create-map.5.x.cs, sync/rest/maps/delete-map-item/delete-map-item.5.x.cs, sync/rest/maps/delete-map/delete-map.5.x.cs, sync/rest/maps/list-maps/list-maps.5.x.cs, sync/rest/maps/query-map/query-map.5.x.cs, sync/rest/maps/retrieve-map-item/retrieve-map-item.5.x.cs, sync/rest/maps/retrieve-map/retrieve-map.5.x.cs, sync/rest/maps/update-map-item/update-map-item.5.x.cs, sync/rest/services/create-service-webhook/create-service-webhook.5.x.cs, sync/rest/services/create-service/create-service.5.x.cs, sync/rest/services/delete-service/delete-service.5.x.cs, sync/rest/services/list-services/list-services.5.x.cs, sync/rest/services/retrieve-service/retrieve-service.5.x.cs, sync/rest/services/update-service/update-service.3.x.js, sync/rest/services/update-service/update-service.5.x.cs
=> Convert Sync C# snippets to beta version

notifications/rest/users/add-user-to-segment/add-user-to-segment.3.x.js, notifications/rest/users/create-user/create-user.3.x.js, notifications/rest/users/list-users/list-user.3.x.js, notifications/rest/users/remove-user-from-segment/remove-user-from-segment.3.x.js, notifications/rest/users/retrieve-user/retrieve-user.3.x.js
=> Fixes errors in Notify REST API docs Node example

rest/accounts/instance-get-example-1/instance-get-example-1.3.x.js, rest/accounts/instance-post-example-1/instance-post-example-1.3.x.js, rest/accounts/instance-post-example-2/instance-post-example-2.3.x.js, rest/accounts/instance-post-example-3/instance-post-example-3.3.x.js, rest/accounts/list-get-example-1/list-get-example-1.3.x.js, rest/accounts/list-get-example-2/list-get-example-2.3.x.js, rest/keys/list-post-example/list-post-example.3.x.js, rest/participant/instance-get-example-1/instance-get-example-1.3.x.js, rest/subaccounts/creating-subaccounts-example-1/creating-subaccounts-example-1.3.x.js, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.3.x.js, rest/subaccounts/listing-subaccounts-example-1/listing-subaccounts-example-1.3.x.js, rest/subaccounts/listing-subaccounts-example-2/listing-subaccounts-example-2.3.x.js, rest/taskrouter/jwts/taskqueue/example-1/example-1.3.x.js, rest/taskrouter/jwts/worker/example-1/example-1.3.x.js, rest/taskrouter/jwts/workspace/example-1/example-1.3.x.js, rest/taskrouter/statistics/taskqueue/example-1/example-1.3.x.js, security/signature_validation/signature_validation.2.x.js, security/signature_validation/signature_validation.3.x.js
Seems PHP specs where fixed with the changes introduced in:
https://github.com/TwilioDevEd/api-snippets/commit/213e1e99f60199fa7c3f6594f2ea5c37dce142e5
https://github.com/TwilioDevEd/api-snippets/commit/4358190292e5b08397acb0a1b10c702beb186e12
=> Fix Node and PHP specs

sync/rest/documents/create-document/create-document.3.x.js, sync/rest/documents/update-document/update-document.3.x.js, sync/rest/lists/create-list-item/create-list-item.3.x.js, sync/rest/lists/update-list-item/update-list-item.3.x.js, sync/rest/maps/create-map-item/create-map-item.3.x.js, sync/rest/maps/update-map-item/update-map-item.3.x.js
JSON.stringify is no longer necessary after https://github.com/TwilioDevEd/sdk-starter-node/pull/15
=> Remove JSON.stringify from Sync node.js snippets

voice/queueing/caller/queue-caller.7.x.java
Fix enqueue sample to use Enqueue instead of Call/Queue
=> Fix Enqueue example Java 7

.gitignore, .travis.yml, README.md, install_travis_dependencies.sh, tools/snippet-testing/language_handler/base_handler.rb, tools/snippet-testing/language_handler/csharp.rb, tools/snippet-testing/language_handler/curl.rb, tools/snippet-testing/language_handler/java.rb, tools/snippet-testing/language_handler/xml_matcher.rb, tools/snippet-testing/model/snippet.rb, tools/snippet-testing/model/test_session.rb, twiml/test.yml
Improve test suite automation to handle twiml code samples to compare its output with plain xml samples.
=> Test Twiml code snippets

guides/request-validation-django/example-1/example-1.5.x.py, guides/request-validation-django/example-3/example-3.5.x.py, guides/request-validation-python/example-1/example-1.5.x.py, guides/request-validation-python/example-3/example-3.5.x.py
@smendes  or @atbaker  do you mind checking this?  The import is straightforward but I had issues validating with (Flask, didn't try Django) both:
https://www.twilio.com/docs/quickstart/python/sms/hello-monkey
And:
https://github.com/pkamp3/twilio-electron-sms-example
If it works I'll fix the Lambda example as well.  I'm using ngrok for both.
=> Update Validation of Twilio requests.

notifications/rest/users/create-user/create-user.5.x.php, notifications/rest/users/create-user/create-user.5.x.rb, notifications/rest/users/create-user/create-user.6.x.py
Fixes 3 languages: Segments --> Segment
=> Notify Create user example fixes

notifications/rest/users/create-user/output/create-user.json, notifications/rest/users/retrieve-user/output/retrieve-user.json
Bindings/USxxx --> Users/USxxx in Create User and Retrieve User output "url"s.
=> Notify: Fixes typos in User resource URLs

rest/recording/get-recording-xml/get-recording-1.3.x.js, rest/recording/get-recording-xml/get-recording-1.5.x.cs, rest/recording/get-recording-xml/get-recording-1.5.x.php, rest/recording/get-recording-xml/get-recording-1.5.x.rb, rest/recording/get-recording-xml/get-recording-1.6.x.py, rest/recording/get-recording-xml/get-recording-1.7.x.java, rest/recording/get-recording-xml/meta.json, tools/snippet-testing/language_handler/ruby.rb
**Add** get recording examples for java, ruby, python, php, c# and js.
=> Add languages get recording

twiml/voice/sim/sim-1/meta.json, twiml/voice/sim/sim-2/meta.json
Disables tests for snippets on:
twiml/voice/sim/sim-1
twiml/voice/sim/sim-2
=> Disables tests for sim's snippets

rest/making-calls/example-4/example-4.3.x.js
=> Passing statusCallbackEvent as array of strings

notifications/register/send-notification-segment/send-notification-segment.3.x.js
=> Fixes Notify guide

.travis.yml, install_travis_dependencies.sh, notifications/rest/notifications/send-passthrough-notification/meta.json, notifications/rest/notifications/send-passthrough-notification/send-passthrough-notification.5.x.php, notifications/rest/notifications/send-passthrough-notification/send-passthrough-notification.5.x.rb, notifications/rest/notifications/send-passthrough-notification/send-passthrough-notification.6.x.py, notifications/rest/notifications/send-passthrough-notification/send-passthrough-notification.7.x.java, notifications/rest/notifications/send-passthrough-notification/send-passthrough-notification.json.curl
Small fixes for a few of the failing CI tests in this repo
=> Fix api snippets errors

authy/mobile-sdk/get-started/get-device-id/get-device-id.java, authy/mobile-sdk/get-started/get-totp/get-totp.java, authy/mobile-sdk/get-started/totp-delegate/totp-delegate.java
Added new code snippets for the Authy Mobile SDK on Android(Java)
=> Updated code snippets for Authy SDK for Android

authy/mobile-sdk/get-started/get-approval-requests/get-approval-requests.java, authy/mobile-sdk/get-started/get-device-id/get-device-id.java, authy/mobile-sdk/get-started/get-totp/get-totp.java, authy/mobile-sdk/get-started/is-device-registered/is-device-registered.java, authy/mobile-sdk/get-started/register-device/register-device.java, authy/mobile-sdk/get-started/register-push-token/register-push-token.java, authy/mobile-sdk/get-started/setup-authy/setup-authy.java
Rename SDK main class from Authy to TwilioAuth
=> Rename Authy SDK to TwilioAuth

deployed-devices/rest/fleets/create-fleet/create-fleet.json.curl, deployed-devices/rest/fleets/create-fleet/meta.json
We're going to have three kinds of snippets in here (I think):
- REST for the Deployed Devices REST API,
- Snippets of on-device code for various common MQTT clients
- Quickstart-specific snippets, perhaps.
=> Snippets for Deployed Devices

ip-messaging/users/token-gen-server-push/token-gen-server-push.3.x.js, ip-messaging/users/token-gen-server-push/token-gen-server-push.5.x.cs, ip-messaging/users/token-gen-server-push/token-gen-server-push.5.x.php, ip-messaging/users/token-gen-server-push/token-gen-server-push.5.x.rb, ip-messaging/users/token-gen-server-push/token-gen-server-push.6.x.py, ip-messaging/users/token-gen-server-push/token-gen-server-push.7.x.java, ip-messaging/users/token-generation-server/token-generation-server.3.x.js, ip-messaging/users/token-generation-server/token-generation-server.5.x.cs, ip-messaging/users/token-generation-server/token-generation-server.5.x.php, ip-messaging/users/token-generation-server/token-generation-server.5.x.rb, ip-messaging/users/token-generation-server/token-generation-server.6.x.py, ip-messaging/users/token-generation-server/token-generation-server.7.x.java, rest/access-tokens/ip-messaging-example/ip-messaging-example.3.x.js, rest/access-tokens/ip-messaging-example/ip-messaging-example.5.x.cs, rest/access-tokens/ip-messaging-example/ip-messaging-example.5.x.php, rest/access-tokens/ip-messaging-example/ip-messaging-example.5.x.rb, rest/access-tokens/ip-messaging-example/ip-messaging-example.6.x.py, rest/access-tokens/ip-messaging-example/ip-messaging-example.7.x.java, tools/snippet-testing/model/dependency.rb
Current snippets are using `IpMessagingGrant` but it was recently deprecated in favor of `ChatGrant`.
=> Replace IpMessagingGrant for ChatGrant

rest/outgoing-caller-ids/list-post-example-1/list-post-example-1.2.x.js
Reverts TwilioDevEd/api-snippets#495 -- Updated legacy snippet instead of next-gen.
=> Revert "DEVED-2520: Update Node.js validationRequests.create"

ip-messaging/rest/messages/send-messages/send-messages.7.x.java, notifications/rest/notifications/send-notification-detailed/send-notification-detailed.3.x.js, notifications/rest/notifications/send-notification-detailed/send-notification-detailed.7.x.java, notifications/rest/notifications/send-notification-with-badge/send-notification-with-badge.3.x.js, notifications/rest/notifications/send-notification-with-badge/send-notification-with-badge.7.x.java, tools/snippet-testing/model/dependency.rb
This PR aligns Java and Node helper libs with latest Twilio SDK release.
=> Notify uses Objects instead of Strings now in Notification resource

guides/request-validation-csharp-web-api/example-1/example-1.4.x.cs, guides/request-validation-csharp-web-api/example-1/meta.json, guides/request-validation-csharp-web-api/example-2/example-2.4.x.cs, guides/request-validation-csharp-web-api/example-2/meta.json, guides/request-validation-csharp-web-api/example-3/example-3.4.x.cs, guides/request-validation-csharp-web-api/example-3/meta.json
These examples will be used in the tutorial for **Secure your C# / ASP.NET app by validating incoming Twilio requests**.
It contains the actual end-points:
- /voice
- /message
And the filter as a custom data annotation.
=> Add examples for request validation using ASP.NET Web API

notifications/sms-quickstart/send-notification-to-number/send-notification-to-number.3.x.js
=> Fixed typo

notifications/register/instance-id-service/instance-id-service.java
Adds an instance id service sample to FCM registration guide
=> Notify - Adds instance id service sample

notifications/register/create-binding-android-2/create-binding-android-2.java
Updates samples to match reworked Android guide
=> Notify Registering for Android guide sample update

quickstart/python/sms/example-8/meta.json, quickstart/python/sms/example-8/reply_to_message.6x.py
For the updated Python SMS Quickstart. A very simple code sample that shows the basics of how to send SMS responses to incoming messages.
I didn't create a 5.x version since my assumption is that anyone who's using a Quickstart (instead of a guide) should be on the latest version of Twilio. Please correct me if my thinking's off here!
=> Add code sample for sending a simple SMS response to incoming messages

quickstart/php/sms/reply_sms/meta.json, quickstart/php/sms/reply_sms/reply_sms.5.x.php, quickstart/php/sms/send_sms/meta.json, quickstart/php/sms/send_sms/send_sms.5.x.php
Send and receive SMS in PHP. Relies on composer.
=> New style PHP Quickstart

rest/call/list-get-example-4/list-get-example-4.5.x.rb
Bringing code into line with caption that says this example should _Only show completed calls started between midnight Jul 04th, 2009 and midnight Jul 06th, 2009._
=> Adding missing parameters

quickstart/python/voice/example-1-make-call/meta.json, quickstart/python/voice/example-1-make-call/outgoing_call.6.x.py, quickstart/python/voice/example-2-receive-call/meta.json, quickstart/python/voice/example-2-receive-call/respond_to_call.6.x.py
Code samples for the new Python quickstart for programmable voice. The Rickroll abides.
=> New code samples for Voice quickstart (Python)

video/rest/recordings/list-deleted-recordings/output/list-deleted-recordings.json, video/rest/recordings/list-recordings-for-participant-in-room/output/list-recordings-for-participant-in-room.json, video/rest/recordings/list-recordings-for-participant/output/list-recordings-for-participant.json, video/rest/recordings/list-recordings-for-room/output/list-recordings-for-room.json, video/rest/recordings/retrieve-recording-binary-data/output/retrieve-recording-binary-data.json, video/rest/recordings/retrieve-recording-by-sid/output/retrieve-recording-by-sid.json
Updated snippets according to current behavior
=> [video-recordings] Update output json snippets

video/rooms/participants/kick-remove-participant/remove-participant.js, video/rooms/participants/kick-remove-participant/remove-participant.php, video/rooms/participants/kick-remove-participant/remove-participant.py, video/rooms/participants/kick-remove-participant/remove-participant.rb, video/rooms/participants/retrieve-participant-list-connected/retrieve-participants-connected.js, video/rooms/participants/retrieve-participant-list-connected/retrieve-participants-connected.php, video/rooms/participants/retrieve-participant-list-connected/retrieve-participants-connected.py, video/rooms/participants/retrieve-participant-list-connected/retrieve-participants-connected.rb, video/rooms/participants/retrieve-participant-list-disconnected/retrieve-participants-disconnected.js, video/rooms/participants/retrieve-participant-list-disconnected/retrieve-participants-disconnected.php, video/rooms/participants/retrieve-participant-list-disconnected/retrieve-participants-disconnected.py, video/rooms/participants/retrieve-participant-list-disconnected/retrieve-participants-disconnected.rb
Fixed snippets for node, python, ruby and php. They were all the same code for `retrieve-a-participant` snippet.
=> DEVED-3119:  Participants /docs shows same code for 4 different cases

two-factor-authentication/verify-webhook/verify-webhook.3.x.js, two-factor-authentication/verify-webhook/verify-webhook.5.x.cs, two-factor-authentication/verify-webhook/verify-webhook.5.x.php, two-factor-authentication/verify-webhook/verify-webhook.5.x.rb, two-factor-authentication/verify-webhook/verify-webhook.6.x.py, two-factor-authentication/verify-webhook/verify-webhook.7.x.java
Updated Python, Ruby, JavaScript and PHP snippets. Previously the Authy request had individual form parameters, now it comes with a JSON body, so it changed the way they have to be read and sorted.
@hortega @joliveros could you give me a hand with Java and C# snippets when you can, please?
=> Updated 2FA Authy verify webhook with new signature verification

rest/taskrouter/jwts/taskqueue/example-1/example-1.3.x.js
TaskRouter TaskQueue Compatibility Token Node.js SDK 3.x API Doc was incorrect
Reference story: https://issues.corp.twilio.com/browse/DEVED-3159
=> Fixed TaskRouter TaskQueue Compatibility Token Node.js SDK 3.x

rest/taskrouter/workflows/instance/delete/example-1/example-1.4.x.rb, rest/taskrouter/workflows/instance/delete/example-1/example-1.5.x.php, rest/taskrouter/workflows/instance/delete/example-1/example-1.5.x.rb, rest/taskrouter/workflows/list/post/example-1/example-1.5.x.php
Related story: https://issues.corp.twilio.com/browse/DEVED-3176
=> /docs/api/taskrouter/workflows missing/incorrect code samples

wireless/quickstart/wio-gsm/Wio-2G-Quickstart.ino
=> New Wio Quickstart

monitor/alerts/instance-delete-example/instance-delete-example.4.x.rb, monitor/alerts/instance-delete-example/instance-delete-example.5.x.rb, monitor/alerts/list-get-example-all/list-get-example-all.4.x.rb, monitor/alerts/list-get-example-all/list-get-example-all.5.x.rb, monitor/alerts/list-get-example-warnings-apr01-apr30/list-get-example-warnings-apr01-apr30.4.x.rb
From #334
If you are interested I could review all the ruby examples
=> Start making prettier ruby example

guides/request-validation-php-lumen/example-2/example-2.5.x.php
Lumen changed to $router in 5.5
=> Change to router references

guides/voice/recording-add-on-guide/use-add-on-data/example.5.x.rb
Finish the work on DEVED-2266, porting the Recording Add-Ons guide to Ruby.
=> Add Ruby example for recording-add-on-guide

guides/voice/recording-add-on-guide/use-add-on-data/example.3.x.js
Finish the work on DEVED-2264, porting the Recording Add-Ons guide to Node.
=> Add Node example for recording-add-on-guide

rest/recording/list-recording-transcriptions/list-recording-transcriptions-3.x.js, rest/recording/list-recording-transcriptions/list-recording-transcriptions-5.x.cs, rest/recording/list-recording-transcriptions/list-recording-transcriptions-5.x.php, rest/recording/list-recording-transcriptions/list-recording-transcriptions-5.x.rb, rest/recording/list-recording-transcriptions/list-recording-transcriptions-7.x.java
Adds sample code for fetching the transcriptions list from a given recording.
This is the continuation for #659
=> Translate "recording transcriptions" code snippet to helper lib languages

rest/messages/generate-twiml-dynamic-sms/generate-twiml-dynamic-sms.7.x.java
Hi, just a little fix to the the java example for dynamic sms response
=> Use .equals instead of == to check message body

rest/conference/list-get-example-4/list-get-example-4.2.x.js, rest/conference/list-get-example-4/list-get-example-4.4.x.cs, rest/conference/list-get-example-4/list-get-example-4.4.x.php, rest/conference/list-get-example-4/list-get-example-4.4.x.rb, rest/conference/list-get-example-4/list-get-example-4.5.x.cs, rest/conference/list-get-example-4/list-get-example-4.5.x.php, rest/conference/list-get-example-4/list-get-example-4.5.x.py, rest/conference/list-get-example-4/list-get-example-4.5.x.rb, rest/conference/list-get-example-4/list-get-example-4.6.x.java, rest/conference/list-get-example-4/list-get-example-4.6.x.py, rest/conference/list-get-example-4/list-get-example-4.7.x.java
Pipe out the SIDs for each conference we fetch this way.
=> Print out conference SIDs from list

video/rest/compositions/get-composition-media-file/get-composition-media-file.6.x.py
The example code below does not work to download the file.
Proposed changes have to do with opening the file and then writing to it.
=> Fix example get composition media file snippet

quickstart/python/understand/example-1/update_initial_intent.6.x.py
Autopilot now using `initiation_actions` for the deafult voice task
=> Update initial task

rest/access-tokens/voice-example/voice-example.3.x.js, rest/access-tokens/voice-example/voice-example.5.x.cs, rest/access-tokens/voice-example/voice-example.5.x.php, rest/access-tokens/voice-example/voice-example.5.x.rb, rest/access-tokens/voice-example/voice-example.6.x.py, rest/access-tokens/voice-example/voice-example.7.x.java
This PR is related to this [ticket](https://issues.corp.twilio.com/browse/DEVED-3510)
=> Show usage of VoiceGrant optional parameter incoming_allow

rest/taskrouter/twiml/example2/example/example.4.x.php, rest/taskrouter/twiml/example2/example/example.5.x.cs, rest/taskrouter/twiml/example2/example/example.5.x.rb, rest/taskrouter/twiml/example2/example/example.6.x.py, rest/taskrouter/twiml/example2/example/example.7.x.java, rest/taskrouter/twiml/example2/example/output/example.xml
File `example.5.x.py` seems fine (tested under twilio==5.7.0)
Fixed `example.6.x.py` (tested under twilio==6.20.0)
Also fixed possible issue with XML syntax in output example, unexpected `/`. 
(not sure if out of the task's scope)
=> Fix python example snippets

wireless/quickstart/m2m_commands_wiolte/m2m_commands_wiolte.ino
New m2m quickstart for the Seeed Studio Wio LTE
=> added m2m_commands_wiolte example

guides/request-validation-python/example-4/example-4.6.x.py, guides/request-validation-python/example-4/meta.json
Sample test to use in security docs to show how to test the validity of a webhook signature
see [VNCORE-2373|https://issues.corp.twilio.com/browse/VCONCORE-2373] for more information
=> Add new code sample to show how to test a webhook signature

security/environment_variables/environment-variables-1.3.x.js, security/environment_variables/environment-variables-1.5.x.cs, security/environment_variables/environment-variables-1.5.x.php, security/environment_variables/environment-variables-1.5.x.rb, security/environment_variables/environment-variables-1.6.x.py, security/environment_variables/environment-variables-1.7.x.java, security/environment_variables/environment-variables.json.curl, security/environment_variables/meta.json
Examples in supported languages for reading environment variables.
=> Environment variable examples

wireless/quickstart/m2m_commands_fona3G/m2m_commands_fona3G.ino, wireless/quickstart/m2m_commands_fona3G/meta.json
New _Wireless_ machine to machine example for the Adafruit FONA 3G board.
=> new m2m - Adafruit FONA 3G

quickstart/php/autopilot/create-first-task/create_hello_world_task.5.x.php, quickstart/php/autopilot/create-hello-world-samples/create_hello_world_samples.5.x.php, quickstart/php/autopilot/create-joke-samples/create_joke_samples.5.x.php, quickstart/php/autopilot/create-joke-task/create_joke_task.5.x.php
- Fixes PHP autopilot quickstart tutorial errors creating tasks
=> Fix autopilot tutorial snippets

wireless/quickstart/m2m_commands_breakout/m2m_commands_breakout.ino, wireless/quickstart/m2m_commands_breakout/meta.json
Quickstart code for m2m_commands_breakout
=> added m2m_commands_breakout

verify/verifications/approve-verification/approve-verification.3.x.js, verify/verifications/approve-verification/approve-verification.5.x.cs, verify/verifications/approve-verification/approve-verification.5.x.php, verify/verifications/approve-verification/approve-verification.5.x.rb, verify/verifications/approve-verification/approve-verification.6.x.py, verify/verifications/approve-verification/approve-verification.7.x.java, verify/verifications/approve-verification/approve-verification.json.curl, verify/verifications/approve-verification/meta.json, verify/verifications/approve-verification/output/approve-verification.json
Adding a snippet to demonstrate how to approve a verification using a phone number instead of a Verification SID.
=> Adding Verification Approval Snippet

guides/voice/respond-incoming-calls-guide/respond-no-parameters/example.3.x.js
Helpful to know the server has started up successfully.
=> Add server startup message

twiml/voice/pay/pay-tokenize/meta.json, twiml/voice/pay/pay-tokenize/output/pay-tokenize.twiml, twiml/voice/pay/pay-tokenize/pay-tokenize.3.x.js, twiml/voice/pay/pay-tokenize/pay-tokenize.5.x.cs, twiml/voice/pay/pay-tokenize/pay-tokenize.5.x.php, twiml/voice/pay/pay-tokenize/pay-tokenize.5.x.rb, twiml/voice/pay/pay-tokenize/pay-tokenize.6.x.py, twiml/voice/pay/pay-tokenize/pay-tokenize.7.x.java
Adds a specific example to call out the importance of setting chargeAmount to 0.
=> Adds a specific tokenization example setting chargeAmount to 0

twiml/voice/stream/stream-1/meta.json, twiml/voice/stream/stream-1/output/stream-1.twiml, twiml/voice/stream/stream-1/stream-1.3.x.js, twiml/voice/stream/stream-1/stream-1.5.x.cs, twiml/voice/stream/stream-1/stream-1.5.x.php, twiml/voice/stream/stream-1/stream-1.5.x.rb, twiml/voice/stream/stream-1/stream-1.6.x.py, twiml/voice/stream/stream-1/stream-1.7.x.java, twiml/voice/stream/stream-2/meta.json, twiml/voice/stream/stream-2/output/stream-2.twiml, twiml/voice/stream/stream-2/stream-2.3.x.js, twiml/voice/stream/stream-2/stream-2.5.x.cs, twiml/voice/stream/stream-2/stream-2.5.x.php, twiml/voice/stream/stream-2/stream-2.5.x.rb, twiml/voice/stream/stream-2/stream-2.6.x.py, twiml/voice/stream/stream-2/stream-2.7.x.java
Adds Stream creation and custom parameter examples
=> Adds Stream TwiML examples.

twiml/voice/siprec/siprec-1/meta.json, twiml/voice/siprec/siprec-1/output/siprec-1.twiml, twiml/voice/siprec/siprec-1/siprec-1.3.x.js, twiml/voice/siprec/siprec-1/siprec-1.5.x.cs, twiml/voice/siprec/siprec-1/siprec-1.5.x.php, twiml/voice/siprec/siprec-1/siprec-1.5.x.rb, twiml/voice/siprec/siprec-1/siprec-1.6.x.py, twiml/voice/siprec/siprec-1/siprec-1.7.x.java
=> Adds <Siprec> TwiML example

quickstart/php/voice/answer_call_without_composer/answer_call.5.x.php, quickstart/php/voice/make_call_without_composer/make_call.5.x.php
the path to autoload.php in the snippets doesn't match the actual directory structure of twilio-php. updating to make this easier for customers
=> fix path to match the actual php repo

guides/request-validation-php-lumen/example-2/example-2.5.x.php, quickstart/php/sms/example-7/send-sms-during-call.5.x.php
=> Uses correct type

rest/taskrouter/twiml/example1/example/example.5.x.php, rest/taskrouter/twiml/example2/example/example.5.x.php, rest/taskrouter/twiml/example3/example/example.5.x.php, rest/taskrouter/twiml/example4/example/example.5.x.php
Fixes https://github.com/twilio/twilio-php/issues/622
=> fix: correct PHP enqueue TwiML args

twiml/voice/connect/stream/connect_stream.3.x.js, twiml/voice/connect/stream/connect_stream.5.x.cs, twiml/voice/connect/stream/connect_stream.5.x.php, twiml/voice/connect/stream/connect_stream.5.x.rb, twiml/voice/connect/stream/connect_stream.6.x.py, twiml/voice/connect/stream/connect_stream.7.x.java, twiml/voice/connect/stream/meta.json, twiml/voice/connect/stream/output/connect_stream.xml
=> Adds Connect Stream TwiML examples

super-sim/sims/update-account/meta.json, super-sim/sims/update-account/output/update-account.json, super-sim/sims/update-account/update-account.3.x.js, super-sim/sims/update-account/update-account.5.x.cs, super-sim/sims/update-account/update-account.5.x.php, super-sim/sims/update-account/update-account.5.x.rb, super-sim/sims/update-account/update-account.6.x.py, super-sim/sims/update-account/update-account.7.x.java, super-sim/sims/update-account/update-account.json.curl
Add Super SIM as a product.  Add snippets for transferring a Super SIM between subaccounts.
=> Add Super SIM product. Add update Sim resource account sid examples.

twiml/voice/parameter/parameter-1/output/parameter-1.twiml, twiml/voice/parameter/parameter-1/parameter-1.3.x.js, twiml/voice/parameter/parameter-1/parameter-1.5.x.cs, twiml/voice/parameter/parameter-1/parameter-1.5.x.php, twiml/voice/parameter/parameter-1/parameter-1.6.x.py, twiml/voice/parameter/parameter-1/parameter-1.7.x.java, twiml/voice/parameter/parameter-1/parameter-5.x.rb
Adds examples of how to use `<Parameter>` TwiML to pass to Voice SDK
=> Adds Parameter Client example

twiml/voice/number/number-5/meta.json, twiml/voice/number/number-5/number-5.3.x.js, twiml/voice/number/number-5/number-5.5.x.cs, twiml/voice/number/number-5/number-5.5.x.php, twiml/voice/number/number-5/number-5.5.x.rb, twiml/voice/number/number-5/number-5.6.x.py, twiml/voice/number/number-5/number-5.7.x.java, twiml/voice/number/number-5/output/number-5.twiml
Adds an example of using the url attribute in the <Number> noun, for [Jira DEVED-4684](https://issues.corp.twilio.com/browse/DEVED-4684)
=> Add <Number url> TwiML example.

twiml/voice/connect/virtualagent/output/basic.twiml, twiml/voice/connect/virtualagent/virtualagent.3.x.js, twiml/voice/connect/virtualagent/virtualagent.5.x.cs, twiml/voice/connect/virtualagent/virtualagent.5.x.php, twiml/voice/connect/virtualagent/virtualagent.5.x.rb, twiml/voice/connect/virtualagent/virtualagent.6.x.py, twiml/voice/connect/virtualagent/virtualagent.7.x.java
These were generated automatically using the twiml-generator tool. https://github.com/TwilioDevEd/twiml-generator
=> Add twiml virtualagent examples.

video/rest/rooms/recording-rules-audio-all/recording-rules-audio-all.json.curl, video/rest/rooms/recording-rules-one-participant/recording-rules-one-participant.json.curl, video/rest/rooms/recording-rules-start-all/recording-rules-start-all.json.curl, video/rest/rooms/recording-rules-stop-all/recording-rules-stop-all.json.curl
Changing to match the Track Subscriptions curl examples.
=> Change the JSON formatting for recording_rules.

video/rest/rooms/recording-rules-audio-all/recording-rules-audio-all.json.curl, video/rest/rooms/recording-rules-one-participant/recording-rules-one-participant.json.curl, video/rest/rooms/recording-rules-start-all/recording-rules-start-all.json.curl, video/rest/rooms/recording-rules-stop-all/recording-rules-stop-all.json.curl
Curl examples still aren't syncing because of an earlier failure. This just adds a space at the end of the samples so they'll be detected as having changed.
=> Update curl code examples so that they'll sync.

guides/voice/gather-dtmf-tones-guide/gather-example-step-1/example.3.x.js, guides/voice/gather-dtmf-tones-guide/gather-example-step-2/example.3.x.js
Chaining pause after say results in an error (`twiml.say(...).pause is not a function`). https://issues.corp.twilio.com/browse/DEVED-5199
=> Fix node example so pause is on a separate line.

guides/request-validation-java/example-1/example-1.7.x.java
https://issues.corp.twilio.com/browse/DEVED-4914
@sarahcstringer
=> DEVED-4914: Twilio-callback-signature-bug-in-Java

rest/voice/generate-twiml-gather/example.8.x.java, rest/voice/generate-twiml-gather/twiml-gather.5.x.cs, rest/voice/generate-twiml-gather/twiml-gather.5.x.rb, rest/voice/generate-twiml-gather/twiml-gather.6.x.py, rest/voice/generate-twiml-gather/twiml-gather.java, rest/voice/generate-twiml-gather/twiml-gather.php, rest/voice/generate-twiml-gather/twiml-gather.xml, rest/voice/generate-twiml-play/example-1.3.x.js, rest/voice/generate-twiml-play/example-1.5.x.cs, rest/voice/generate-twiml-play/example-1.6.x.py, rest/voice/generate-twiml-play/example-1.xml, rest/voice/generate-twiml-play/twiml-play.5.x.rb, rest/voice/generate-twiml-play/twiml-play.8.x.java, rest/voice/generate-twiml-play/twiml-play.php, rest/voice/generate-twiml-record/twiml-record.3.x.js, rest/voice/generate-twiml-record/twiml-record.5.x.cs, rest/voice/generate-twiml-record/twiml-record.5.x.rb, rest/voice/generate-twiml-record/twiml-record.6.x.py, rest/voice/generate-twiml-record/twiml-record.8.x.java, rest/voice/generate-twiml-record/twiml-record.php
This change replaces existing S3-hosted sample asset URLs with Twilio Runtime Assets hosted asset URLs.
=> Update soundbyte URLs to use MP3 files hosted by Twilio Assets

ip-messaging/media/check-presence-media/check-presence-media.m, ip-messaging/media/check-presence-media/check-presence-media.swift, ip-messaging/media/create-media-message/create-media-message.m, ip-messaging/media/create-media-message/create-media-message.swift, ip-messaging/media/retrieve-message-media/retrieve-message-media.m, ip-messaging/media/retrieve-message-media/retrieve-message-media.swift
Update snippets for media messages handling in iOS SDK 2.1.0 release.
=> feat: update snippets for media ios

ip-messaging/reachability-indicator/process-user-updates/process-user-updates.js, rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.3.x.js, rest/taskrouter/jwts/worker/example-1/example-1.2.x.js, video/rest/compositions/compose-mosaic/compose-mosaic.3.x.js, video/rest/rooms/recording-rules-audio-all/recording-rules-audio-all.3.x.js, video/rest/rooms/recording-rules-one-participant/recording-rules-one-participant.3.x.js, video/rest/rooms/recording-rules-start-all/recording-rules-start-all.3.x.js, video/rest/rooms/recording-rules-stop-all/recording-rules-stop-all.3.x.js
This PR fixes the linter issues present in the new GH actions implementation for the NodeJS code snippets.
The new GH actions implementation is done here: https://github.com/TwilioDevEd/api-snippets/pull/946
The tests errors are not being fixed in this PR only the linter errors.
Changes:
* Fix linter issues for NodeJS code snippets.
=> Fix node snippets linter issues

rest/messages/generate-twiml-dynamic-sms/generate-twiml-dynamic-sms.3.x.js, rest/messages/generate-twiml-mms/generate-twiml-mms.3.x.js, rest/messages/generate-twiml-sms/generate-twiml-sms.3.x.js
Getting ready to write Golang versions of these, and realized the Express samples are using some janky methods / involve more typing than necessary 👀
=> Tidy messaging express

add-ons/VoicemailTutorial/VoicemailEkataPhoneValid.js, add-ons/VoicemailTutorial/VoicemailNoAddOns.js
DEVED-7670 outlines creation of a tutorial using Twilio Functions in order to create a voicemail
=> Addition of two code samples needed for DEVED-7670

rest/voice/generate-twiml-say/generate-twiml-say.1.x.go
Voice quickstart server in Golang: TwiML + Say examples
=> feat: add initial samples for voice/say in Go

guides/request-validation-csharp-core/example-1/example-1.cs, guides/request-validation-csharp-core/example-2/example-2.cs, guides/request-validation-csharp-core/example-3/example-3.cs
This code improves the existing solution by:
- retrieving the configuration using dependency injection, instead of rebuilding it from a specific JSON file.
- load the form asynchronously
=> Use DI for configuration + load form async

mobile-identity/silent-network-auth/create-an-evurl/create-an-evurl-example.4.x.js, mobile-identity/silent-network-auth/create-an-evurl/create-an-evurl-example.5.x.cs, mobile-identity/silent-network-auth/create-an-evurl/create-an-evurl-example.5.x.rb, mobile-identity/silent-network-auth/create-an-evurl/create-an-evurl-example.6.x.php, mobile-identity/silent-network-auth/create-an-evurl/create-an-evurl-example.7.x.py, mobile-identity/silent-network-auth/create-an-evurl/create-an-evurl-example.9.x.java, mobile-identity/silent-network-auth/create-an-evurl/create-an-evurl-example.json.curl, mobile-identity/silent-network-auth/retrieve-evurl-result/retrieve-evurl-result-example.4.x.js, mobile-identity/silent-network-auth/retrieve-evurl-result/retrieve-evurl-result-example.5.x.cs, mobile-identity/silent-network-auth/retrieve-evurl-result/retrieve-evurl-result-example.5.x.rb, mobile-identity/silent-network-auth/retrieve-evurl-result/retrieve-evurl-result-example.6.x.php, mobile-identity/silent-network-auth/retrieve-evurl-result/retrieve-evurl-result-example.7.x.py, mobile-identity/silent-network-auth/retrieve-evurl-result/retrieve-evurl-result-example.9.x.java, mobile-identity/silent-network-auth/retrieve-evurl-result/retrieve-evurl-result-example.json.curl
Added new parameters to existing code samples
=> DEVED-8237: Added parameters to mobile-identity code samples

twiml/voice/say/ssml/ssml.4.x.js
Update break_ method to break() to match updates in Node Helper Library
=> Change break_ to break

messaging/content-templates/create-wa-otp-button-template/create-wa-otp-button-template.curl, messaging/content-templates/create-wa-otp-button-template/meta.json, messaging/content-templates/create-wa-otp-button-template/output/create-wa-otp-button-template.json
=> Add WA OTP template example

messaging/content-templates/create-a-quick-reply-template/create-a-quick-reply-template.curl, messaging/content-templates/create-a-quick-reply-template/meta.json, messaging/content-templates/create-a-quick-reply-template/output/create-a-quick-reply-template.json
=> Quick reply template sample

messaging/content-templates/create-call-to-action-template/create-call-to-action-template.curl, messaging/content-templates/create-call-to-action-template/meta.json, messaging/content-templates/create-call-to-action-template/output/create-call-to-action-template.json
=> Add cta templates

messaging/content-templates/create-card-template/create-card-template.curl, messaging/content-templates/create-card-template/meta.json, messaging/content-templates/create-card-template/output/create-card-template.json
=> Add card template examples

messaging/content-templates/create-media-template/create-media-template.curl, messaging/content-templates/create-media-template/meta.json, messaging/content-templates/create-media-template/output/create-media-template.json
=> Add media templates sample

messaging/content-templates/create-text-template/create-text-template.curl, messaging/content-templates/create-text-template/create-text-template.java, messaging/content-templates/create-text-template/meta.json, messaging/content-templates/create-text-template/output/create-text-template.json
=> Add text template examples

messaging/content-templates/use-content-variables/meta.json, messaging/content-templates/use-content-variables/output/use-content-variables.json, messaging/content-templates/use-content-variables/use-content-variables.curl
=> Add variables examples

messaging/content-templates/create-a-quick-reply-template/meta.json, messaging/content-templates/create-call-to-action-template/meta.json, messaging/content-templates/create-card-template/meta.json, messaging/content-templates/create-list-picker-template/meta.json, messaging/content-templates/create-location-template/meta.json, messaging/content-templates/create-media-template/meta.json, messaging/content-templates/create-text-template/meta.json, messaging/content-templates/create-wa-otp-button-template/meta.json, messaging/content-templates/use-content-variables/meta.json
Add "type": "server" to the meta files and remove other stuff. The docs platform doesn't like it.
=> Fix meta files

messaging/content-templates/create-whatsapp-card/create-whatsapp-card.curl, messaging/content-templates/create-whatsapp-card/meta.json, messaging/content-templates/create-whatsapp-card/output/create-whatsapp-card.json
=> Add WA Card template examples

messaging/content-templates/submit-a-template-for-whatsapp-approval/meta.json, messaging/content-templates/submit-a-template-for-whatsapp-approval/output/submit-a-template-for-whatsapp-approval.json, messaging/content-templates/submit-a-template-for-whatsapp-approval/submit-a-template-for-whatsapp-approval.curl
Add a Content Template sample over from docs repo.
=> Add whatsapp approvalrequest sample

messaging/content-templates/fetch-all-content-resources/fetch-all-content-resources-example.json.curl, messaging/content-templates/fetch-all-content-resources/meta.json, messaging/content-templates/fetch-all-content-resources/output/fetch-all-content-resources.json
More Content Templates samples
=> Add fetch all content resources samples

messaging/content-templates/create-catalog-static-items/create-catalog-static-items.curl, messaging/content-templates/create-catalog-static-items/meta.json, messaging/content-templates/create-catalog-static-items/output/create-catalog-static-items.json
Another Content Template example
=> Add catalog static samples

messaging/content-templates/create-catalog-template-dynamic-items/create-catalog-template-dynamic-items.curl, messaging/content-templates/create-catalog-template-dynamic-items/meta.json, messaging/content-templates/create-catalog-template-dynamic-items/output/create-catalog-template-dynamic-items.json
Another Content Template snippet
=> Add dynamic products catalog template
