TwilioDevEd/api-snippets

tools/snippet-testing/find_unused_snippets.rb

Find out which snippets are not in use in the CMS and delete them if necessary.

Find unused snippets in the CMS

---

rest/taskrouter/reservations/call/example-1.cs
rest/taskrouter/reservations/dequeue/example-1.cs
rest/taskrouter/reservations/redirect/example-1.cs

C# code snippets are currently missing on TaskRouter Update a Reservation REST docs for Call, Dequeue, Redirect instructions.

Adding c# examples for call, dequeue, and redirect

---

notifications/register/receive-notification-android/receive-notification-android.java

From Oct 3 2016, GCM notifications are by default data messages with the Body parameter translated to twi_body in the data bundle. This change adjusts the code sample to reflect that.

Adjusts to handle default data message

---

rest/taskrouter/jwts/workspace/example-1/example-1.2.x.js
rest/taskrouter/jwts/workspace/example-1/example-1.3.x.js

Node examples for TaskRouter.js Workspace incorrectly uses TaskRouterTaskQueueCapability(). Changing to TaskRouterWorkspaceCapability().

Switching to TaskRouterWorkspaceCapability()

---

video/getting-started/connect-to-room/connect-to-room.m
video/getting-started/connect-to-room/connect-to-room.swift
video/getting-started/create-video-client/create-video-client.m
video/getting-started/create-video-client/create-video-client.swift
video/getting-started/handle-participants/handle-participants.m
video/getting-started/handle-participants/handle-participants.swift
video/rooms/create-room/create-room.m
video/rooms/create-room/create-room.swift
video/rooms/disconnect-from-room/disconnect-from-room.m
video/rooms/disconnect-from-room/disconnect-from-room.swift
video/rooms/display-participants-video/display-participants-video.m
video/rooms/display-participants-video/display-participants-video.swift
video/rooms/handle-participant-events/handle-participant-events.m
video/rooms/handle-participant-events/handle-participant-events.swift
video/rooms/join-room/join-room.m
video/rooms/join-room/join-room.swift

**iOS TwilioVideo 1.0.0-beta9 changes:** 
It is no longer necessary to create a TVIVideoClient. Instead there is a class method which connects to a Room.

iOS TwilioVideo 1.0.0-beta9 changes

---

rest/messages/generate-twiml-sms/meta.json
rest/outgoing-caller-ids/list-post-example-1/meta.json
rest/taskrouter/jwts/workspace/example-1/example-1.3.x.js
tools/snippet-testing/language_handler/base_handler.rb

Build fix: disable node.js snippets

---

video/getting-started/setup-local-media/setup-local-media.m

Hi, I found this piece of code confusing on [your guide](https://www.twilio.com/docs/api/video/getting-started) so I think that the best is to remove it:
```
// Connect and share your local media
TVIRoom *room = [videoClient connectWithOptions:connectOptions delegate:self];
```
- videoClient is not declared above so it's misleading and doesn't compile.
- there's no interaction between `videoClient` and `localMedia` so I don't see the point of declaring that piece of code in that snippet.

Fixed 'Setup Local Media' (ObjC)

---

notifications/register/create-binding-server-apns/create-binding.js
notifications/register/create-binding-server/create-binding.js
notifications/register/send-notification-1/send-notification-1.js
notifications/register/send-notification-2/send-notification-2.js
notifications/register/send-notification/send-notification.js
notifications/sms-quickstart/create-binding/example.js
notifications/sms-quickstart/send-notification/example.js

https://issues.corp.twilio.com/browse/DEVED-2191
When setting the Notify client, refer to 'notify' instead of 'notifications':
Old: var service = client.notifications.v1.services('ISxxx')
New: var service = client.notify.v1.services('ISxxx')
I did double-check that we're using the appropriate client.notify syntax in all other languages for these code samples.

Change old 'notifications' property to 'notify'

---

notifications/rest/bindings/create-binding/create-binding.5.x.cs
notifications/rest/bindings/create-binding/create-binding.7.x.java

The binding type for these snippets should be apn, not gcm.

Change binding type to apn in C# and Java snippets(notify)

---

rest/accounts/instance-get-example-1/instance-get-example-1.3.x.js
rest/accounts/instance-get-example-1/instance-get-example-1.5.x.php
rest/accounts/instance-post-example-1/instance-post-example-1.3.x.js
rest/accounts/instance-post-example-1/instance-post-example-1.5.x.php
rest/accounts/instance-post-example-2/instance-post-example-2.3.x.js
rest/accounts/instance-post-example-2/instance-post-example-2.5.x.php
rest/accounts/instance-post-example-3/instance-post-example-3.3.x.js
rest/accounts/instance-post-example-3/instance-post-example-3.5.x.php
rest/accounts/list-get-example-1/list-get-example-1.3.x.js
rest/accounts/list-get-example-1/list-get-example-1.5.x.php
rest/accounts/list-get-example-2/list-get-example-2.3.x.js
rest/accounts/list-get-example-2/list-get-example-2.5.x.php
rest/subaccounts/creating-subaccounts-example-1/creating-subaccounts-example-1.3.x.js
rest/subaccounts/creating-subaccounts-example-1/creating-subaccounts-example-1.5.x.php
rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.3.x.js
rest/subaccounts/exchanging-numbers-example-1/exchanging-numbers-example-1.5.x.php
rest/subaccounts/listing-subaccounts-example-1/listing-subaccounts-example-1.3.x.js
rest/subaccounts/listing-subaccounts-example-1/listing-subaccounts-example-1.5.x.php
rest/subaccounts/listing-subaccounts-example-2/listing-subaccounts-example-2.3.x.js
rest/subaccounts/listing-subaccounts-example-2/listing-subaccounts-example-2.5.x.php

Any Node.js, PHP, Python, and Ruby snippets that access the Account resource, like the snippets on this page: https://www.twilio.com/docs/api/rest/account
Need to be updated to use the full api namespace (e.g. `client.api.v2010.accounts` instead of `client.accounts`).
See this issue for background:
https://github.com/twilio/twilio-node/issues/251

Fixing accounts resource

---

sync/rest/documents/create-document/create-document.php
sync/rest/documents/update-document/update-document.php
sync/rest/lists/create-list-item/create-list-item.php
sync/rest/lists/update-list-item/update-list-item.php
sync/rest/maps/create-map-item/create-map-item.php
sync/rest/maps/update-map-item/update-map-item.php

`json_encode` is no longer necessary after https://github.com/TwilioDevEd/sdk-starter-php/pull/17

Remove json_encode from Sync PHP snippets

---

notifications/rest/bindings/create-binding/create-binding.json.curl
notifications/rest/bindings/list-binding/list-binding.json.curl
notifications/rest/credentials/create-fcm-credential/create-fcm-credential.json.curl
notifications/rest/credentials/create-gcm-credential/create-gcm-credential.json.curl

Many fields in Create Binding request supports unicode and hence need to be url encoded.

Adds url encoding to Notify Create Binding curl example

---

rest/incoming-phone-numbers/instance-get-example-1/output/instance-get-example-1.json

Noticed there was a missing comma in the code example for `incomingPhoneNumber` resource response. Fixed it!

Add missing comma in JSON

---

deployed-devices/quickstarts/paho-python/meta.json
deployed-devices/quickstarts/paho-python/subscribe-and-print.py

This will replace the inline code block [here](https://www.twilio.com/docs/quickstart/python-mqtt-quickstart#subscribe-to-the-sync-document-from-mqtt).
I'm actually concerned that the file extension doesn't match the constraints of Wagtail. This snippet does not use the helper library, so mentioning a version number would be nonsense.

Add the quickstart snippet for Paho/Python MQTT connection.

---

guides/request-validation-csharp-web-api/example-1/example-1.4.x.cs
guides/request-validation-csharp-web-api/example-3/example-3.4.x.cs

This pull request removes the dependencies introduced through https://github.com/twilio/twilio-aspnet. So that this implementation depends solely on the Twilio C# SDK.

Make use of RequestValidator dependency

---

guides/request-validation-csharp/example-1/example-1.4.x.cs
guides/request-validation-csharp/example-2/example-2.4.x.cs
guides/request-validation-csharp/example-3/example-3.4.x.cs

This pull request updates the code snippets for the guide [**Secure Your C# / ASP.NET App By Validating Incoming Twilio Requests**](https://www.twilio.com/docs/guides/how-to-secure-your-csharp-aspnet-app-by-validating-incoming-twilio-requests).
The previous examples didn't use either `VoiceRequest` nor `MessagingRequest`.
Moreover, the `ValidateTwilioRequestAttribute` was refactored to make it more idiomatic.

Update validate request guide

---

guides/request-validation-csharp-core/example-1/example-1.4.x.cs
guides/request-validation-csharp-core/example-1/meta.json
guides/request-validation-csharp-core/example-2/example-2.4.x.cs
guides/request-validation-csharp-core/example-2/meta.json
guides/request-validation-csharp-core/example-3/example-3.4.x.cs
guides/request-validation-csharp-core/example-3/meta.json

The examples in this pull request will be used in the tutorial **Secure your C# / ASP.NET Core App by Validating Incoming Twilio Requests**.

Add request validation for C# .NET Core

---

video/rest/recordings/retrieve-recording-binary-data/retrieve-recording-binary-data.3.x.js

This fixes a couple of issues with this sample, as discovered in this [Stack Overflow question](https://stackoverflow.com/questions/46588223/issue-downloading-twilio-recording-in-twilio-rooms).
* `client.request` returns a promise rather than running synchronously
* requesting a media resource should be by `GET` not `POST`

Corrects video dowloading example code

---

video/rest/recordings/retrieve-recording-binary-data/retrieve-recording-binary-data.5.x.cs
video/rest/recordings/retrieve-recording-binary-data/retrieve-recording-binary-data.5.x.php
video/rest/recordings/retrieve-recording-binary-data/retrieve-recording-binary-data.5.x.rb
video/rest/recordings/retrieve-recording-binary-data/retrieve-recording-binary-data.6.x.py
video/rest/recordings/retrieve-recording-binary-data/retrieve-recording-binary-data.7.x.java

Requesting a media resource should be by _GET_.
**TODO**
Update the examples for the languages:

Corrects video downloading examples

---

rest/test-credentials/test-incoming-phone-numbers-example-1/output/test-incoming-phone-numbers-example-1.json

These make Google think this page was published/last updated in 2012. Not good for building confidence in our docs

Remove date-created dates

---

rest/messages/generate-twiml-dynamic-sms/generate-twiml-dynamic-sms.5.x.rb
rest/messages/generate-twiml-sms/generate-twiml-sms.5.x.rb

The latest `Message` object in TwiML requires a hash with a `body` rather than plain text.

Fixes `MessagingResponse`

---

rest/change-call-state/example-1/example-1.5.x.rb

Shouldn't be running a .fetch since it could potentially fail here due to the eventual consistency on the calls resource

Remove fetch() from POST call in ruby SDK

---

notifications/register/create-binding-server-apns/create-binding-server-apn.5.x.php

twilio/sdk/Twilio/Rest/Notify/V1/Service/BindingList.php requires three input parameters. Endpoint is part of the options array. The example before had endpoint as the first input parameter. Sending 5 input attributes to the function returns an error.

BindingList function parameter

---

rest/call/list-get-example-3/list-get-example-3.5.x.php
rest/call/list-get-example-4/list-get-example-4.5.x.php

Updated startTimeAfter and startTimeBefore to reflect the correct syntax as defined in the PHP Helper library.

Updated PHP get call list examples

---

client/capability-token-incoming/capability-token.6.x.py

Old method was `generate()`, it's now `to_jwt()`

Update capability token creation method

---

quickstart/python/sms/example-8/reply_to_message.5x.py

While I'm increasingly on the side of us only showing the latest lib in Quickstarts, I want to keep this consistent with the other samples for now - and, this way, the code can be reused on other parts of the docs where we do want to give the 5.x option.

Add 5.x example

---

proxy/quickstart/create-participant/create-participant.5.x.php
proxy/quickstart/create-service/create-service.5.x.php

The proxy quickstart examples in this PR were using the incorrect parameter names. And are now using the correct ones. 
resolves #604

fix php proxy quickstart examples

---

rest/taskrouter/jwts/workspace/example-1/example-1.3.x.js

Right now in the docs we are referencing a WorkerSid when generating a Workspace JWT. Both the channelId and and policy should reference the WorkspaceSid instead

TaskRouter JWT Workspace Channel Change

---

twiml/message/your-response/your-response-1/output/your-response-1.twiml
twiml/message/your-response/your-response-1/your-response-1.3.x.js
twiml/message/your-response/your-response-1/your-response-1.5.x.cs
twiml/message/your-response/your-response-1/your-response-1.5.x.php
twiml/message/your-response/your-response-1/your-response-1.5.x.rb
twiml/message/your-response/your-response-1/your-response-1.6.x.py
twiml/message/your-response/your-response-1/your-response-1.7.x.java

The existing URL in this sample (https://demo.twilio.com/sms/welcome) 404s. It should be https://demo.twilio.com/welcome/sms/.

fix redirect with URL that does not 404

---

deployed-devices/quickstarts/paho-python/publish.py

- Fix client tls_set call
- Fix MyFirstDocument name
- Add comments regarding trusted CA roots location
- Add example for publishing document updates

Improve Paho MQTT examples for Sync for IoT

---

rest/messages/sms-handle-callback/sms-handle-callback.3.x.js

Calling `res.end` without any other actions on the `res` will send a response without a content type. Twilio will complain about that with a warning in the debugger.
`res.sendStatus(200);` will set the content type to `text/plain` and the body to "OK". It also has more intention in it ("I want to send a successful response").

Change res.end to res.sendStatus

---

rest/recording/get-recording-xml/get-recording-xml.7.x.java

Recording fetcher expects parameter 2 to  be recording_id, auth_token is passed instead.

bugfix: pass RECORDING_ID instead of AUTH_TOKEN

---

quickstart/php/taskrouter/accept-reservation/accept-reservation.5.x.php

update('accept') will throw errors. I think it's because the reservation api has changed.

Fixed grammar issue

---

lookups/lookup-get-basic-example-1/lookup-get-basic-example-1.3.x.js
lookups/lookup-get-basic-example-1/lookup-get-basic-example-1.5.x.cs
lookups/lookup-get-basic-example-1/lookup-get-basic-example-1.5.x.php
lookups/lookup-get-basic-example-1/lookup-get-basic-example-1.5.x.rb
lookups/lookup-get-basic-example-1/lookup-get-basic-example-1.6.x.py
lookups/lookup-get-basic-example-1/lookup-get-basic-example-1.7.x.java

Lookups API does something that other APIs don't do – it returns an HTTP 404 when it can't find the carrier info for a number, which results in a runtime exception in helper libraries.
https://www.twilio.com/docs/api/lookups
Each code sample (for every language) on this page should demonstrate how to catch the runtime exception and check for the 404.

lookups code samples should demonstrate catching the 404 exception

---

rest/messages/generate-twiml-dynamic-sms/generate-twiml-dynamic-sms.3.x.js

This change will fix the following body-parser deprecation warnings that appear in the console:
```
body-parser deprecated bodyParser: use individual json/urlencoded middlewares app.js:56:9
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:105:29
```

Add .urlencoded to bodyParser to fix deprecation warnings

---

rest/taskrouter/jwts/taskqueue/example-1/example-1.5.x.cs

The current C# sample for "Creating a TaskRouter TaskQueue capability token" has 2 errors. 
1. The channel parameter of TaskRouterCapability constructor should be passed the TaskQueue Sid rather than null. A value of null causes an Exception  
`System.NullReferenceException occurred
HResult=0x80004003
Message=Object reference not set to an instance of an object.
Source=<Cannot evaluate the exception source>
StackTrace:
at Twilio.Jwt.Taskrouter.TaskRouterCapability.get_Claims()
at Twilio.Jwt.BaseJwt.ToJwt()`
2. There is a typo in the TaskQueue property of PolicyUrlUtils. The URL should have TaskQueues instead of TaskQueue
Fixing these 2 changes makes the sample work correctly. Current sample causes this [issue](https://stackoverflow.com/questions/46783017/error-in-twilio-net-sdk-making-task …

Fix C# snippet to generate TaskRouter TaskQueue Capability Token

---

lookups/lookup-get-carrier-cname-example-1/lookup-get-carrier-cname-example-1.6.x.py
lookups/lookup-get-cname-example-1/lookup-get-cname-example-1.6.x.py

The caller_name lookup examples are trying to print the carrier data.  Fix the
print statements for the response data to reference the correct dict object.
I found this inconsistency while trying to use the API examples to test CID Lookups from our PBX connected to the Elastic SIP Trunking.

Fix CID Name Python Examples

---

guides/voice/recording-add-on-guide/use-add-on-data/example.6.x.py

The `Response()` class was returning the following error:
```python
AttributeError: module 'twilio.twiml' has no attribute 'Response'
```
This PR uses VoiceResponse to fix it.

Import VoiceResponse instead of getting Response from twilio.twiml

---

guides/voice/recording-add-on-guide/use-add-on-data/example.5.x.php

Finish the work on DEVED-2265, porting the Recording Add-Ons guide to PHP.
I used the Slim framework, which seems like Flask/Express, being more related to the other guides.

Add PHP example for recording-add-on-guide

---

quickstart/php/taskrouter/agent/agent.4.x.php
quickstart/php/taskrouter/agent/agent.5.x.php
rest/taskrouter/reservations/conference/example-1.2.x.js
rest/taskrouter/reservations/conference/example-1.3.x.js
rest/taskrouter/reservations/conference/example-1.4.x.cs
rest/taskrouter/reservations/conference/example-1.4.x.php
rest/taskrouter/reservations/conference/example-1.4.x.rb
rest/taskrouter/reservations/conference/example-1.5.x.cs
rest/taskrouter/reservations/conference/example-1.5.x.php
rest/taskrouter/reservations/conference/example-1.5.x.py
rest/taskrouter/reservations/conference/example-1.5.x.rb
rest/taskrouter/reservations/conference/example-1.6.x.java
rest/taskrouter/reservations/conference/example-1.6.x.py
rest/taskrouter/reservations/conference/example-1.7.x.java
rest/taskrouter/reservations/conference/example-1.json.curl

The goal of the conference updates was to stop using 'dequeueFrom' as the example parameter (and get rid of the trailing comma). I added ConferenceStatusCallback because this is a very common help request we get from customers, and it has not been clear how to successfully add them. The examples for each language are largely derived from https://www.twilio.com/docs/voice/make-calls#make-a-call-and-monitor-progress-events and https://www.twilio.com/docs/voice/api/conference-participant#participants-list-resource, with a few references from the helper libraries to figure out the expected types for TaskRouter-specific methods.
These snippets have not been tested against the libraries.

Update TaskRouter JS version and Conference examples

---

twiml/voice/dial/dial-2/output/dial-2.twiml

This url isn't in this TwiML sample, which can lead to confusion.

Remove unnecessary docstring

---

guides/request-validation-csharp/example-1/example-1.cs

RawUrl only returns content after the url following the domain information. The request calculation should be based on the full Url which AbsoluteUri returns.

Change RawUrl to AbsoluteUri

---

guides/request-validation-csharp/example-3/example-3.cs

The original code would return 403/Forbidden if `AppSettings["IsTestEnvironment"]` was set to "true"

Fix conditional order

---

wireless/quickstart/m2m_commands_arduino_sim800/SIM800Twilio.cpp
wireless/quickstart/m2m_commands_arduino_sim800/SIM800Twilio.hpp
wireless/quickstart/m2m_commands_arduino_sim800/m2m_commands_arduino_sim800.ino
wireless/quickstart/m2m_commands_arduino_sim800/meta.json
wireless/quickstart/m2m_commands_feather32u4fona/m2m_commands_feather32u4fona.ino
wireless/quickstart/m2m_commands_feather32u4fona/meta.json

I added a new Quickstart to Wireless:
m2m_commands_feather32u4fona
- This is an example of how to create M2M commands using the Adafruit Feather 32u4 FONA board. The code follows the same paradigm as the Arduino/SIM800 example.
m2m_commands_arduino_sim800
- Added this back since I messed up the CMS yesterday. Good to go.

added m2m_commands_feather32u4fona

---

rest/taskrouter/twiml/example4/example/example.3.x.js

Per https://issues.corp.twilio.com/browse/DEVED-3483, enqueueTask() no longer works – the lib now expects .enqueue()

Update snippet to use .enqueue

---

security/signature_validation/signature_validation.2.x.js
security/signature_validation/signature_validation.3.x.js
security/signature_validation/signature_validation.4.x.php
security/signature_validation/signature_validation.4.x.rb
security/signature_validation/signature_validation.5.x.cs
security/signature_validation/signature_validation.5.x.php
security/signature_validation/signature_validation.5.x.py
security/signature_validation/signature_validation.5.x.rb
security/signature_validation/signature_validation.6.x.java
security/signature_validation/signature_validation.6.x.py
security/signature_validation/signature_validation.7.x.java

While replacing test numbers, the signatures weren't updated so the validation snippets were all invalid.
Also, Ruby prefers `puts` to `print`.

Updates signatures for validation snippets.

---

client/capability-token-2way/capability-token.6.x.py
client/capability-token-outgoing/capability-token.6.x.py
client/capability-token/capability-token.6.x.py

`generate` is not a method of ClientCapabilityToken or the base class JWT.

Use `to_jwt` method instead of erroneous `generate` call

---

ip-messaging/tokens/initialization/initialization.java
ip-messaging/tokens/initialization/initialization.js
ip-messaging/tokens/initialization/initialization.m
ip-messaging/tokens/initialization/initialization.swift
ip-messaging/tokens/initialization/meta.json
ip-messaging/tokens/renewal/meta.json
ip-messaging/tokens/renewal/renewal.java
ip-messaging/tokens/renewal/renewal.js
ip-messaging/tokens/renewal/renewal.m
ip-messaging/tokens/renewal/renewal.swift
ip-messaging/tokens/update/meta.json
ip-messaging/tokens/update/update.java
ip-messaging/tokens/update/update.js
ip-messaging/tokens/update/update.m
ip-messaging/tokens/update/update.swift

Particularly addressing three scenarios:
- initializing the client with initial token
- updating the token with provided string
- using the built-in token lifecycle events

Adding snippets for Chat token management

---

rest/messages/generate-twiml-sms/generate-twiml-sms.5.x.php

I need to update many more snippets as it seems that `Twilio\Twiml` is deprecated in favour of creating specific handlers. I'm not 100% that this is the new way to use the library but once this is confirmed and merged I can update more snippets.

Updated deprecated code in sms Twiml generation

---

ip-messaging/reachability-indicator/process-user-updates/process-user-updates.js

This commit fixes an incorrect event name, changing `userInfoUpdated` to `userUpdated`, as described in the [Chat SDK documentation](https://media.twiliocdn.com/sdk/js/chat/releases/3.2.3/docs/Client.html#event:userUpdated__anchor).

IPM-1898: Change userInfoUpdated to userUpdated

---

ip-messaging/reachability-indicator/process-user-updates/meta.json
ip-messaging/reachability-indicator/process-user-updates/process-user-updates.js

This commit updates the Reachability indicator ("Process a UserInfo Update") code sample to listen for the `updated` event on the User, rather than the `userUpdated` event on the chatClient.

[DEVED-4075] Update Reachability code sample

---

guides/request-validation-php-lumen/example-1/example-1.5.x.php

Example was written before request body validation was add to the PHP helper lib. This update switches to sending the request content when the `bodySHA256` param is detected.

Add JSON body request validation support to PHP

---

two-factor-authentication/verify-webhook/verify-webhook.3.x.js

Without the fix the comparator function is comparing the full array not only the key of the property.
```javascript
// x = 'property=value';
const xx = x.split('=');
// xx will be an Array['property', 'value']
```
```javascript
// x = 'property=value';
const xx = x.split('=')[0]; // 'property'
// xx will be the first element of the array
```

Fix sortByPropertyOnly to compare the property

---

quickstart/php/sms/reply_sms_without_composer/reply_sms.5.x.php

As per https://github.com/twilio/twilio-php/issues/513#issuecomment-438929412, "the correct TwiML code is to use the namespace Twilio\TwiML with a VoiceResponse or MessagingResponse class."

The Twiml class is deprecated.

---

client/capability-token-2way/capability-token.5.x.rb
client/capability-token-expires/capability-token-expires.5.x.rb
client/capability-token-incoming/capability-token.5.x.rb
client/capability-token-outgoing/capability-token.5.x.rb
client/capability-token/capability-token.5.x.rb

Relates to https://github.com/twilio/twilio-ruby/issues/501

fix: correct the Ruby client capability token examples

---

ip-messaging/users/token-generation-server/token-generation-server.3.x.js
rest/access-tokens/ip-messaging-example/ip-messaging-example.3.x.js
rest/access-tokens/video-example/video-example.3.x.js
rest/access-tokens/voice-example/voice-example.3.x.js
video/users/token-generation-server-rooms/token-generation-server.3.x.js
video/users/token-generation-server/token-generation-server.3.x.js

Fixes https://github.com/twilio/twilio-node/issues/579
The `identity` property is not accessible via the TS definition but can be set using the constructor (along with `ttl` and `nbf`).

fix: correct the Node AccessToken examples to be more compatible with TypeScript

---

twiml/voice/refer/refer-1/refer-1.3.x.js
twiml/voice/refer/refer-1/refer-1.5.x.cs
twiml/voice/refer/refer-1/refer-1.6.x.py
twiml/voice/refer/refer-1/refer-1.7.x.java
twiml/voice/refer/refer-2/refer-2.3.x.js
twiml/voice/refer/refer-2/refer-2.5.x.cs
twiml/voice/refer/refer-2/refer-2.6.x.py
twiml/voice/refer/refer-2/refer-2.7.x.java
twiml/voice/refer/refer-3/refer-3.3.x.js
twiml/voice/refer/refer-3/refer-3.5.x.cs
twiml/voice/refer/refer-3/refer-3.6.x.py
twiml/voice/refer/refer-3/refer-3.7.x.java
twiml/voice/refer/refer-4/refer-4.3.x.js
twiml/voice/refer/refer-4/refer-4.5.x.cs
twiml/voice/refer/refer-4/refer-4.5.x.php
twiml/voice/refer/refer-4/refer-4.6.x.py
twiml/voice/refer/refer-4/refer-4.7.x.java

`referSip` methods were deprecated; code samples should be updated to reflect this.
(Context from the `twilio-java` library: https://github.com/twilio/twilio-java/blob/main/UPGRADE.md#changed---renamed-nested-twiml-methods)
These code samples were automatically generated and verified with the Twilio twiml generator (https://github.com/TwilioDevEd/twiml-generator).

Fix referSip code samples.

---

twiml/voice/dial/dial-9/dial-9.3.x.js
twiml/voice/dial/dial-9/dial-9.5.x.cs
twiml/voice/dial/dial-9/dial-9.5.x.rb
twiml/voice/dial/dial-9/dial-9.6.x.php
twiml/voice/dial/dial-9/dial-9.6.x.py
twiml/voice/dial/dial-9/dial-9.7.x.java
twiml/voice/dial/dial-9/meta.json
twiml/voice/dial/dial-9/output/dial-9.twiml

Adds a new example for the REFER to Twilio page: https://www.twilio.com/docs/voice/api/refer-to-twilio

Adds referUrl example with answerOnBridge

---

twiml/voice/connect/virtualagent-2/virtualagent-2.6.x.py
twiml/voice/connect/virtualagent-3/meta.json
twiml/voice/connect/virtualagent-3/output/connect_virtualagent_3.twiml
twiml/voice/connect/virtualagent-3/virtualagent-3.3.x.js
twiml/voice/connect/virtualagent-3/virtualagent-3.5.x.cs
twiml/voice/connect/virtualagent-3/virtualagent-3.5.x.php
twiml/voice/connect/virtualagent-3/virtualagent-3.5.x.rb
twiml/voice/connect/virtualagent-3/virtualagent-3.6.x.py
twiml/voice/connect/virtualagent-3/virtualagent-3.7.x.java
twiml/voice/connect/virtualagent-3/virtualagent.3.x.js
twiml/voice/connect/virtualagent-3/virtualagent.5.x.cs
twiml/voice/connect/virtualagent-3/virtualagent.5.x.php
twiml/voice/connect/virtualagent-3/virtualagent.5.x.rb
twiml/voice/connect/virtualagent-3/virtualagent.6.x.py
twiml/voice/connect/virtualagent-3/virtualagent.7.x.java
twiml/voice/connect/virtualagent-4/meta.json
twiml/voice/connect/virtualagent-4/output/connect_virtualagent_4.twiml
twiml/voice/connect/virtualagent-4/virtualagent-4.3.x.js
twiml/voice/connect/virtualagent-4/virtualagent-4.5.x.cs
twiml/voice/connect/virtualagent-4/virtualagent-4.5.x.php
twiml/voice/connect/virtualagent-4/virtualagent-4.5.x.rb
twiml/voice/connect/virtualagent-4/virtualagent-4.6.x.py
twiml/voice/connect/virtualagent-4/virtualagent-4.7.x.java
twiml/voice/connect/virtualagent/virtualagent.6.x.py

One for changing an agent's language, and one for turning on Sentiment Analysis.

Add two more VirtualAgent examples.

---

rest/messages/generate-twiml-sms/generate-twiml-sms.5.x.php

https://twilio.zendesk.com/agent/tickets/6000658
As per https://github.com/twilio/twilio-php/blob/main/src/Twilio/TwiML/TwiML.php, the namespace should be `Twilio\TwiML`.

Reported error from customer

---

video/rest/compositions/get-composition-media-file/get-composition-media-file.json.curl

Fix the incorrect URL in the curl example for get-composition-media-file.

[VIDEO-5254] Fix incorrect curl URL in compositions example.

---

rest/messages/sms-handle-callback/sms-handle-callback.5.x.cs

This commit replaces `SmsSid` (deprecated but remains for backwards compatibility) with `MessageSid` in the C# codesample for handling an SMS StatusCallback.

[DEVED-4355] Replace SmsSid with MessageSid

---

video/rest/compositions/get-composition-media-file/get-composition-media-file.3.x.js

Jira: https://issues.corp.twilio.com/browse/DEVED-5693
https://www.twilio.com/docs/video/api/compositions-resource#get-composition-media-file-http-get
Using `response.data` returns undefined. This should be accessing `response.body`.

DEVED-5693: Fix incorrect example for nodejs getting composition media.

---

twiml/voice/parameter/parameter-1/output/parameter-1.twiml
twiml/voice/parameter/parameter-1/parameter-1.3.x.js
twiml/voice/parameter/parameter-1/parameter-1.5.x.cs
twiml/voice/parameter/parameter-1/parameter-1.5.x.php
twiml/voice/parameter/parameter-1/parameter-1.6.x.php
twiml/voice/parameter/parameter-1/parameter-1.6.x.py
twiml/voice/parameter/parameter-1/parameter-1.7.x.java
twiml/voice/parameter/parameter-1/parameter-1.8.x.java
twiml/voice/parameter/parameter-1/parameter-5.x.rb

As per the warning on [this page:](https://www.twilio.com/docs/voice/twiml/client) "The client identifier currently may only contain alpha-numeric and underscore characters."
This PR updates the snippets from 'user-jane' to 'user_jane' to reduce confusion for the user.

Update client identifier to use underscores instead of hyphens

---

rest/usage-records/list-get-example-1/list-get-example-1.2.x.cli
rest/usage-records/list-get-example-2/list-get-example-2.2.x.cli
rest/usage-records/list-get-example-3/list-get-example-3.2.x.cli
rest/usage-records/list-get-example-4/list-get-example-4.2.x.cli
rest/usage-records/list-get-example-5/list-get-example-5.2.x.cli

This change adds Twilio CLI 2.x samples to the existing collection of samples that illustrate how to list [Usage Records](https://www.twilio.com/docs/usage/api/usage-record#).

Add samples for listing Usage Records with Twilio CLI

---

guides/voice/gather-dtmf-tones-guide/gather-example-step-0/example.5.x.cs
guides/voice/gather-dtmf-tones-guide/gather-example-step-1/example.5.x.cs
guides/voice/gather-dtmf-tones-guide/gather-example-step-2.1/example.5.x.cs
guides/voice/gather-dtmf-tones-guide/gather-example-step-2/example.5.x.cs

Update C# DTMF guide examples to include action Uri, TwiMLResult, VoiceRequest, and correct Gather syntax.

Update C# DTMF guide examples

---

rest/access-tokens/sync-example/meta.json
rest/access-tokens/sync-example/sync-example.3.x.js
rest/access-tokens/sync-example/sync-example.5.x.cs
rest/access-tokens/sync-example/sync-example.5.x.php
rest/access-tokens/sync-example/sync-example.5.x.rb
rest/access-tokens/sync-example/sync-example.6.x.py
rest/access-tokens/sync-example/sync-example.8.x.java

Propose the below code snippet to add to the docs here: https://www.twilio.com/docs/iam/access-tokens#
I'll also submit the WagTail request once code has been merged

Sync examples

---

rest/messages/feedback-confirm/feedback-confirm.3.x.js

I was using node.js and it was not working for me, then I checked how it was in other languages and I saw this was wrongly being used there. I guess the account SID is already set in the `client` instantiation.

remove wrong call to 'accounts' method

---

guides/functions/joke-function/joke-function.3.x.js
guides/functions/jokes-function/jokes-function.3.x.js

Part of our revamp of the Runtime docs has included consistently using ES6 arrow functions as well as making sure users get in the habit of using `return callback` instead of just `callback`. It's not technically an issue for these examples, but it helps with the consistency of our samples and messaging :)

fix: standardize Runtime mobile sample code

---

video/rest/rooms/participants/unsubscribe-media-transcriber/meta.json
video/rest/rooms/participants/unsubscribe-media-transcriber/output/update-customer-rules.json
video/rest/rooms/participants/unsubscribe-media-transcriber/update-customer-rules.3.x.js
video/rest/rooms/participants/unsubscribe-media-transcriber/update-customer-rules.5.x.cs
video/rest/rooms/participants/unsubscribe-media-transcriber/update-customer-rules.5.x.rb
video/rest/rooms/participants/unsubscribe-media-transcriber/update-customer-rules.6.x.php
video/rest/rooms/participants/unsubscribe-media-transcriber/update-customer-rules.7.x.py
video/rest/rooms/participants/unsubscribe-media-transcriber/update-customer-rules.8.x.java
video/rest/rooms/participants/unsubscribe-media-transcriber/update-customer-rules.json.curl

This essentially copies the code from [an existing code sample](https://github.com/TwilioDevEd/api-snippets/tree/master/video/rest/rooms/participants/update-subscribe-rules-static) and only changes the specific rule being applied.

Add example for subscribing a Media Transcriber to a single Room Participant.

---

guides/request-validation-gin/example-1/example-1.1.x.go
guides/request-validation-gin/example-1/meta.json
guides/request-validation-gin/example-2/example-2.1.x.go
guides/request-validation-gin/example-2/meta.json
rest/messages/generate-twiml-dynamic-sms/generate-twiml-dynamic-sms.1.x.go
rest/messages/generate-twiml-mms/generate-twiml-mms.1.x.go
rest/messages/generate-twiml-sms/generate-twiml-sms.1.x.go

Adds Golang support for Messaging TwiML samples, such as when running a server that needs to respond to an incoming message with an SMS/MMS in kind.
Also adds example servers for validating incoming webhook requests

feat: add Go samples for messaging twiml + validation examples

---

twiml/voice/connect/virtualagent-5/meta.json
twiml/voice/connect/virtualagent-5/output/connect_virtualagent_5.twiml
twiml/voice/connect/virtualagent-5/virtualagent-5.3.x.js
twiml/voice/connect/virtualagent-5/virtualagent-5.5.x.cs
twiml/voice/connect/virtualagent-5/virtualagent-5.5.x.rb
twiml/voice/connect/virtualagent-5/virtualagent-5.6.x.php
twiml/voice/connect/virtualagent-5/virtualagent-5.6.x.py
twiml/voice/connect/virtualagent-5/virtualagent-5.8.x.java
twiml/voice/connect/virtualagent-6/meta.json
twiml/voice/connect/virtualagent-6/output/connect_virtualagent_6.twiml
twiml/voice/connect/virtualagent-6/virtualagent-6.3.x.js
twiml/voice/connect/virtualagent-6/virtualagent-6.5.x.cs
twiml/voice/connect/virtualagent-6/virtualagent-6.5.x.rb
twiml/voice/connect/virtualagent-6/virtualagent-6.6.x.php
twiml/voice/connect/virtualagent-6/virtualagent-6.6.x.py
twiml/voice/connect/virtualagent-6/virtualagent-6.8.x.java

Adds code samples for <Param> and <Config> nouns within <VirtualAgent>.
The Node.js example doesn't currently work because of a bug in the helper library, but I've tested the other examples.

Add Dialogflow CX VirtualAgent examples.

---

rest/messages/generate-twiml-sms/generate-twiml-sms.1.x.go

This snippet gives a compiler warning that you cannot assign an error type to a string, err.Error() casts it correcty and allows it to compile. 
Original code gives this compiler error: cannot use err (variable of type error) as string value in argument to context.String

Fix compiler error on line 20

---

rest/messages/generate-twiml-dynamic-sms/generate-twiml-dynamic-sms.1.x.go
rest/messages/generate-twiml-mms/generate-twiml-mms.1.x.go

As discovered by #997, some of my messaging-related samples were passing `err` directly instead of calling `err.Error()` (embarrassing since I did it corectly with `err.Error()` in the Voice and request validation samples 🤦 ). Fixing this for remaining Golang samples while it's on my mind :)

fix: incorrect error casting to string

---

twiml/voice/say/ssml/ssml.5.x.rb

Addresses an issue in the sample code for ruby + prosody: https://github.com/twilio/twilio-ruby/issues/637
edit: this should be future-proof at least for the upcoming release, since the (admittedly, terrible) [argument setup](https://github.com/twilio/twilio-ruby/blob/6.0.0-rc/lib/twilio-ruby/twiml/voice_response.rb#L596) is maintained 🙃

fix: ruby prosody argument for words

---

content-api/call-to-action/call-to-action-example.json.curl
content-api/call-to-action/meta.json
content-api/call-to-action/output/call-to-action.json

Add Call to Action code sample for the Content API product per #help-docs request to match CMS-only code snippet here https://www.twilio.com/docs/admin/snippets/code_samples/codesample/edit/4530/. 
The problem with the CMS-only code snippet is that different spacing is showing up in the code snippet when used on the doc vs when it's viewed solitarily as a code snippet in the CMS.
https://twilio.slack.com/archives/C0M0WNMST/p1679338245304039

Add Call to Action code sample for the Content API product

---

rest/access-tokens/ip-messaging-example/ip-messaging-example.1.x.go
rest/access-tokens/sync-example/sync-example.1.x.go
rest/access-tokens/sync-example/sync-example.8.x.py
rest/access-tokens/video-example/video-example.1.x.go
rest/access-tokens/voice-example/voice-example.1.x.go

Create examples for Voice/Video/Sync/IP-Messaging Access Tokens using the Go Helper Library.
Also fixes a snippet of NodeJS code within the Python Sync example.

Go access token examples

---

messaging/services/service-list/output/service-list.json

Fixes the difference between the curl request being made pageSize attribute and the example response posted on docs.

Fix pageSize attribute value to be consistent with curl example

---

rest/notification/list-get-example-4/meta.json

This missing parameter is making fail the option to update all scripts.

Add missing parameter on rest.notification.list-get-example-4.meta.json

---

security/signature_validation/signature_validation.1.x.go
security/signature_validation/signature_validation.4.x.js
security/signature_validation/signature_validation.6.x.cs
security/signature_validation/signature_validation.6.x.rb
security/signature_validation/signature_validation.7.x.php
security/signature_validation/signature_validation.8.x.py
security/signature_validation/signature_validation.9.x.java

Hopefully this will help prevent brittle integrations.

Add explicit warning comment in webhook security examples

---

rest/access-tokens/ip-messaging-example-push-credential/ip-messaging-example.1.x.go
rest/access-tokens/ip-messaging-example-push-credential/ip-messaging-example.4.x.js
rest/access-tokens/ip-messaging-example-push-credential/ip-messaging-example.6.x.cs
rest/access-tokens/ip-messaging-example-push-credential/ip-messaging-example.6.x.rb
rest/access-tokens/ip-messaging-example-push-credential/ip-messaging-example.7.x.php
rest/access-tokens/ip-messaging-example-push-credential/ip-messaging-example.8.x.py
rest/access-tokens/ip-messaging-example-push-credential/ip-messaging-example.9.x.java
rest/access-tokens/ip-messaging-example-push-credential/meta.json

These code samples are copied directly from [this example set](https://github.com/TwilioDevEd/api-snippets/tree/master/rest/access-tokens/ip-messaging-example) and I added the pushCredentialSid to each ChatGrant.
I've tested these to make sure they run.

Add examples for creating ChatGrants with push credentials.

---

voice/specify-edge/meta.json
voice/specify-edge/specify-edge.1.x.go
voice/specify-edge/specify-edge.4.x.js
voice/specify-edge/specify-edge.6.x.cs
voice/specify-edge/specify-edge.6.x.rb
voice/specify-edge/specify-edge.7.x.php
voice/specify-edge/specify-edge.8.x.py
voice/specify-edge/specify-edge.9.x.java

https://issues.corp.twilio.com/browse/DEVED-8517
Takes the code samples from this page https://www.twilio.com/docs/global-infrastructure/create-an-outbound-call-via-rest-api-in-a-non-us-twilio-region and puts them into this repo.
The Tabbed Content component in Wagtail only supports up to 6 code samples, so I can't add another one for Go in the existing doc as it is.
I tested the new Go code sample, and the others are taken directly from the docs.

Move code snippets from docs to GitHub

---

rest/messages/generate-twiml-empty-response/generate-twiml-empty-response.1.x.go
rest/messages/generate-twiml-empty-response/generate-twiml-empty-response.4.x.js
rest/messages/generate-twiml-empty-response/generate-twiml-empty-response.6.x.cs
rest/messages/generate-twiml-empty-response/generate-twiml-empty-response.6.x.rb
rest/messages/generate-twiml-empty-response/generate-twiml-empty-response.7.x.php
rest/messages/generate-twiml-empty-response/generate-twiml-empty-response.8.x.py
rest/messages/generate-twiml-empty-response/generate-twiml-empty-response.9.x.java
rest/messages/generate-twiml-empty-response/meta.json

[DEVED-5017](https://issues.corp.twilio.com/browse/DEVED-5017)
Show how to respond to an incoming message request with nothing (by not sending a message back and just receiving the message).
I copied these from the existing [generate-twiml-sms](https://github.com/TwilioDevEd/api-snippets/tree/master/rest/messages/generate-twiml-sms) examples and altered them to send a blank TwiML response.

Create example for responding to incoming message with empty TwiML.

---

guides/request-validation-php-lumen/example-1/meta.json
guides/request-validation-php-lumen/example-3/meta.json

This characters in the tittle or description are making fail the serialisation of some pages.

[Fix] Remove backticks for general usage pages serialisation

---

messaging/content-templates/create-list-picker-template/create-list-picker-template.curl
messaging/content-templates/create-list-picker-template/meta.json
messaging/content-templates/create-list-picker-template/output/create-list-picker-template.json

Add list picker content templates sample

---

messaging/content-templates/create-location-template/create-location-template.curl
messaging/content-templates/create-location-template/meta.json
messaging/content-templates/create-location-template/output/create-location-template.json

Add content templates location samples

---

twiml/voice/transcription/transcription-hints-tokens/meta.json
twiml/voice/transcription/transcription-hints/meta.json
twiml/voice/transcription/transcription-inboundtracklabel-outboundtracklabel/meta.json
twiml/voice/transcription/transcription-languagecode/meta.json
twiml/voice/transcription/transcription-name/meta.json
twiml/voice/transcription/transcription-partialresults/meta.json
twiml/voice/transcription/transcription-profanityfilter/meta.json
twiml/voice/transcription/transcription-speechmodel/meta.json
twiml/voice/transcription/transcription-stop/meta.json
twiml/voice/transcription/transcription-track/meta.json
twiml/voice/transcription/transcription-transcriptionengine/meta.json

Add backslashes to attempt to stop docs platform from throwing MDX errors when rendering the code samples with `<` or `>`

Add backslashes
